### ISSUE TITLE
Memory leak in dwm.exe

### ISSUE THREAD

**Issue by Crescr** [MicaForEveryone/MicaForEveryone#101]
Setting the global rule to "Acrylic" from the initial settings will greatly increase the commit size of dwm.exe.
It quickly exceeds 500MB just by repeatedly maximizing the window, and if left for a few days, it will eat up the memory.
This is almost the same phenomenon as the bug that existed in Intel's old UHD driver.
If it is set to "Mica", the problem does not occur.

22621.290
3070 Ti 516.79

**Comment by xmine64** [comment]
Report it to Microsoft.
