### ISSUE TITLE
Black window on launch

### ISSUE THREAD

**Issue by dr-baba** [MicaForEveryone/MicaForEveryone#106]
The exe zip version has started to fail to open. I am running v1.1.0.5 on Windows 11 Beta Channel. I have ran this version since release and has only failed today.

This is what opens when launching (after which it closes/crashes):

![image](https://user-images.githubusercontent.com/50979846/182812859-a2c4c789-4f91-4bd3-a90b-e2e619e7610b.png)

I have switched to msix bundle for now which works but is not ideal as I can't run as admin etc.

**Comment by xmine64** [comment]
> This is what opens when launching

I'm not sure what's wrong abd I'm not even on beta channel to debug it, but it may get fixed with a later update of Windows.

> not ideal as I can't run as admin

You should be able to run it as admin.

**Comment by xmine64** [comment]
Is it still reproducible?

**Comment by dr-baba** [comment]
Yes, still only the .msix works for me, the .exe and .zip both have black windows.

Additionally, now It doesn't let me run the "C:\Program Files\WindowsApps\MicaForEveryone_1.2.0.0_x64__pfhyqtmn5ksmy\MicaForEveryone\MicaForEveryone.exe" which I used in a script to run as admin at login through Task Scheduler. Only opening through start menu/auto start app option works now.

Is there a way to automatically run as admin on startup (quite a few programs aren't mica unless ran as admin)?

**Comment by dongle-the-gadget** [comment]
From what I know, directly referencing the EXE path won't work, you would need to target the app execution alias.

**Comment by xmine64** [comment]
> Yes, still only the .msix works for me, the .exe and .zip both have black windows.

Maybe you're missing a dependency?

> Is there a way to automatically run as admin on startup (quite a few programs aren't mica unless ran as admin)?

Use this: `%LocalAppData%\Microsoft\WindowsApps\mfe.exe`

**Comment by xmine64** [comment]
I'll close this. If you have installed [Visual C++ Runtimes v140](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022) and still you have this problem reopen it.
