### ISSUE TITLE
Crash (.Net Issue ?)

### ISSUE THREAD

**Issue by CroissantDuNord** [MicaForEveryone/MicaForEveryone#107]
I cant start the program

Event Log
![image](https://user-images.githubusercontent.com/79372025/182832493-5ab89659-2caf-4858-80eb-7d394ed3ba81.png)

**Comment by dongle-the-gadget** [comment]
Ah yes that dependency bug strikes again.

**Comment by xmine64** [comment]
> Ah yes that dependency bug strikes again.

That's my Inno Setup script's problem, I already know how to fix it but I forgot to do it.
