### ISSUE TITLE
Slightly Rounded don't have shadows under windows

### ISSUE THREAD

**Issue by chuck00000** [MicaForEveryone/MicaForEveryone#109]
Slightly Rounded

![{D5A728AF-97EB-48BE-84E7-EA0DD6BB0070}](https://user-images.githubusercontent.com/98159699/183055622-3c7724c1-46b4-4322-8cab-3a9eb9357179.png)

Rounded

![{FB50EDAC-0DC3-450D-9EF3-44517167407C}](https://user-images.githubusercontent.com/98159699/183055695-7f37f369-5e47-4f03-8fe0-98aca64113a2.png)

Square

![{2015C145-6E8D-4864-B608-797330704C2B}](https://user-images.githubusercontent.com/98159699/183055781-9e25ab4d-f70b-412b-b335-32ae2534a0aa.png)

**Comment by dongle-the-gadget** [comment]
Probably third-party, since MFE doesn't change shadows. Windows does.
