### ISSUE TITLE
HDR Issues with the Extend Frame Into Client Area and Behind Blur Feature

### ISSUE THREAD

**Issue by Weather-OS** [MicaForEveryone/MicaForEveryone#113]
_Previously at https://github.com/MicaForEveryone/MicaForEveryone/issues/61_ But this issue is only solvable by disabling both options.

Please look into this issue.

**Comment by dongle-the-gadget** [comment]
Not something we can really change, I'm afraid.

**Comment by Weather-OS** [comment]
What seems to cause the problem?

**Comment by dongle-the-gadget** [comment]
The only way MFE manipulates the windows is via changing stuff in Windows API.
And also blur behind is an unsupported scenario. Many things break with it on.

**Comment by Weather-OS** [comment]
Hmm. I'm gonna see what I can do.

**Comment by Weather-OS** [comment]
Yeah you are right. It only applies a flag to `HRESULT DwmSetWindowAttribute(DWORD   dwAttribute)`. The only way it could be fixed is if it was patched at a low level.

**Comment by Weather-OS** [comment]
Well, I think that's it. I have no authority to decompile, patch and redistribute the File Uxtheme.dll under Microsoft's Terms and conditions. Unless I reverse engineer it which I have no idea how to do. 

This issue is now marked as closed.
