### ISSUE TITLE
Solid color  on text

### ISSUE THREAD

**Issue by da3dsoul1** [MicaForEveryone/MicaForEveryone#116]
Overall mica works great, but I have an issue with apps like keepass, qbittorrent, etc. The tilebar is mica except for the text, it has solid color behind it, any way I can fix this? I'm on 22000.318
![image](https://user-images.githubusercontent.com/111184581/184495205-5633c759-faf4-45d2-ac1e-98592f6bbe75.png)
![image](https://user-images.githubusercontent.com/111184581/184495231-3c74b3a6-3efc-42ce-b43c-72b2e8567a9d.png)
![image](https://user-images.githubusercontent.com/111184581/184495324-07ab4d46-c920-4434-a7f2-5fb298a32472.png)

**Comment by dongle-the-gadget** [comment]
[RTFM!](wiki/FAQ#theres-a-whiteblack-rectangle-on-titlebar)
