### ISSUE TITLE
Error 0xe0434352 during launch attempt

### ISSUE THREAD

**Issue by itzbluebxrry** [MicaForEveryone/MicaForEveryone#117]
I'm on build 22621.1 RP and I can't launch mfe. Here's the error:-
![image](https://user-images.githubusercontent.com/99461083/184523487-b72e3df6-31a1-4e0b-b4cd-255429ecb767.png)

**Comment by xmine64** [comment]
Is it still reproducible? Are you using packaged version or unpackaged? Is it first time that you run it? Do you have .NET Core 3.1 installed? I can't guess what can be wrong.

**Comment by xmine64** [comment]
I close this as there's no response from reporter.
