### ISSUE TITLE
Is there a way to disable completely for an particular app? 

### ISSUE THREAD

**Issue by lvlzyro** [MicaForEveryone/MicaForEveryone#120]
Is there a way to make MFE not able to effect and application. I dont mean making settings to default and none, I mean totally disabling it for a single application. Because it causes a hole on the upper left corner for terminal (it goes off when I turn MFE off) and it really bothers me.
![terminal_bug](https://user-images.githubusercontent.com/45663782/185760500-fb355f80-bde1-4b1f-ae86-bf4863982add.png)

**Comment by dongle-the-gadget** [comment]
Creating a new rule for that application and setting everything to Default and Off is the only way I'm aware of right now. From what I remember, MFE doesn't make any changes to the window beyond what's shown in the UI.

Check if you have any class or process rule that has "Cascadia" (Windows Terminal codename) in the name. If there is any, change its settings.

Also. make sure that the rule is the top rule in the configuration file, since otherwise some other rule may override it.

**Comment by dongle-the-gadget** [comment]
Turns out that hole isn't recognized by Spy++, which would make it somewhat harder for me to troubleshoot.

**Comment by dongle-the-gadget** [comment]
Figured it out, that "hole" is hosted by OpenConsole, not Cascadia. Adding a Default rule for OpenConsole.exe solves this problem. I'll add OpenConsole into the default configuration file as a workaround for now.

The long-term solution is to, well, improve the exclusion check in MFE itself. There's also an issue where if you use WPF debugging in Visual Studio, it may cause the window to go completely blank.

**Comment by dongle-the-gadget** [comment]
`9a8d61f` introduces the new rule.

**Comment by dongle-the-gadget** [comment]
Mentioning @xmine64 here as well.

**Comment by lvlzyro** [comment]
@dongle-the-gadget tried `OpenConsole` too, and it worked. Thanks for help!

**Comment by KrazyLurt** [comment]
This issue is back on my system again, even with OpenConsole
Windows 11 build 22621.963 (latest stable)

**Comment by dongle-the-gadget** [comment]
Are you using Windows Terminal stable or preview?

**Comment by KrazyLurt** [comment]
> Are you using Windows Terminal stable or preview?

Windows Terminal stable v1.15.3466.0 (Windows 11), it just got updated

**Comment by seanmamasde** [comment]
> > Are you using Windows Terminal stable or preview?
> 
> Windows Terminal stable v1.15.3466.0 (Windows 11), it just got updated

I am also using the same version, stable channel.

**Comment by Chris123NT** [comment]
> > > Are you using Windows Terminal stable or preview?
> > 
> > 
> > Windows Terminal stable v1.15.3466.0 (Windows 11), it just got updated
> 
> I am also using the same version, stable channel.

add pwsh.exe to remove it now, that worked for me for powershell 7, or the windows powershell exe if using that. I also added conhost for good measure as well as WindowsTerminal.exe.
