### ISSUE TITLE
Don’t　launch Windows11

### ISSUE THREAD

**Issue by array** [MicaForEveryone/MicaForEveryone#123]
After install,don't launch on Windows11.
Nothing do this.

**Comment by dongle-the-gadget** [comment]
I don't understand what you mean.

**Comment by lebao3105** [comment]
> I don't understand what you mean.

He tried to run MicaForEveryone on Windows 11 but nothing happends. I have the same problem now.

**Comment by dongle-the-gadget** [comment]
Were you using the Inno Setup (Installer.exe) installer?

**Comment by lebao3105** [comment]
Yes, both Release and Debug installer. However, use the temporary solution [here](https://github.com/MicaForEveryone/MicaForEveryone/issues/104) @array.

**Comment by dongle-the-gadget** [comment]
@xmine64 managed to fix the problem, but the change hasn't been published IIRC.

(I hate the `runtimes` folder, it's the cause of almost all launch problems)

**Comment by foursplaysroblox** [comment]
i was about to install mica for everyone but i did not install it when i saw this untill it is fixed.

**Comment by Pein1911** [comment]
Same here

**Comment by dongle-the-gadget** [comment]
I would recommend that you guys use the MSIX version for the time being, as the Inno Setup file is rather buggy.

**Comment by xmine64** [comment]
I close this as I fixed the installer in this [commit](https://github.com/MicaForEveryone/MicaForEveryone/commit/ad8b58b7fd0be51aac349e50b148ac028bf73bd7) and a new version is released.
