### ISSUE TITLE
can't install 1.2.0 (0x800B010A)

### ISSUE THREAD

**Issue by MuscularPuky** [MicaForEveryone/MicaForEveryone#132]
maybe it needs "MicaForEveryone.pfx" but the password is locked so i can't import keyl.

**Comment by dongle-the-gadget** [comment]
Don't use `MicaForEveryone.pfx`. Just install it to Local Machine > Trusted People by right clicking the MSIX file > Properties > Digital Signature.

**Comment by MuscularPuky** [comment]
Thanks! Windows still saying it's untrusted but anyway it's works.
