### ISSUE TITLE
Korean translations not appearing in 1.2.0.0

### ISSUE THREAD

**Issue by RTFTR** [MicaForEveryone/MicaForEveryone#134]
So i heard that my translations for this app has been added. But when i checked it, It wasn't there.
![image](https://user-images.githubusercontent.com/83257329/190611081-eec4b6e9-82b4-4db5-b404-eeaac99e4c44.png)

**Comment by xmine64** [comment]
You didn't do it properly and I didn't notice. Will get fixed soon.
