### ISSUE TITLE
Mica For Everyone does not open

### ISSUE THREAD

**Issue by SlavBoi420** [MicaForEveryone/MicaForEveryone#136]
It is as simple as that. Mica For Everyone does not open when I use the executable. It seems to try and open, but then closes itself. There is no window or anything visible nor anything on the system tray. 

I tried using both the zip and the installer executable and got the same result.

**Comment by rangan2510** [comment]
Can you try once with your AV disabled?
________________________________
From: SlavBoi420 ***@***.***>
Sent: Tuesday, September 20, 2022 11:29 AM
To: MicaForEveryone/MicaForEveryone ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MicaForEveryone/MicaForEveryone] Mica For Everyone does not open (Issue #136)


It is as simple as that. Mica For Everyone does not open when I use the executable. It seems to try and open, but then closes itself. There is no window or anything visible nor anything on the system tray.

I tried using both the zip and the installer executable and got the same result.

**Comment by xmine64** [comment]
>  Mica For Everyone does not open when I use the executable.

Do you have .NET Core 3.1 and WinUI package installed? Maybe some dependencies are missing.

> Can you try once with your AV disabled?

What does it have with AV?

**Comment by dongle-the-gadget** [comment]
And also, have you tried the MSIX version yet? Seems to be the most reliable even though that might be because almost nobody uses MSIX.

**Comment by SlavBoi420** [comment]
> Can you try once with your AV disabled?

I don't think my AV is causing any problems as it did a full scan earlier on and found no threats

> Do you have .NET Core 3.1 installed? Maybe some dependencies are missing.

I had the runtimes already installed, but then I installed the SDK as well (v3.1.423, x64), yet I still can't open MicaForEveryone 

> And also, have you tried the MSIX version yet?

I will try this, but it is kinda odd that both .exe and .zip files are not getting installed properly

**Comment by xmine64** [comment]
> Maybe because we used some hacks or something that broke XAML Islands when running unpackaged?

It works on my machine™
