### ISSUE TITLE
Border on the left and top sides of the screen during full screen video playback on Firefox

### ISSUE THREAD

**Issue by fieraoh** [MicaForEveryone/MicaForEveryone#138]
A mica blurred border appears when full screening a video on Firefox

![Screenshot 2022-09-24 214722](https://user-images.githubusercontent.com/72320316/192116588-04343d41-3884-4660-ad0a-82aa32aff9bd.png)

Remarks:
The issue has nothing to do with the Wavefox theme as the issue persists with it disabled.
The issue is not present in chromium based browsers.

**Comment by Marcoooooo** [comment]
I uninstalled mfe, but the effect still there.

**Comment by xmine64** [comment]
> A mica blurred border appears when full screening a video on Firefox

Third-party problems, try finding class name of that window and create a rule for it in MFE.

> I uninstalled mfe, but the effect still there.

Restart Firefox once.

**Comment by fieraoh** [comment]
The issue has nothing to do with MicaForEveryone I will publish an issue on the WaveFox github page
