### ISSUE TITLE
MicaForEveryone not run on windows 10 21H2?

### ISSUE THREAD

**Issue by RaoufAdel** [MicaForEveryone/MicaForEveryone#141]
when run MicaForEveryone.exe it show me this messege: to run  this application you must install.NET  Core.
and ask me to would you like download it I press yes and nothing happen! any help here ?

**Comment by xmine64** [comment]
As @Kiridono22 mentioned, you need to install .NET Core 3.1. This will change as soon as we move to C++.
For Windows 10 support check #65, despite the main features won't work on Windows 10 but still we provide some basic limited suppport for features that are available on Windows 10. Right now the configuration UI may not work properly but we will work on it.
