### ISSUE TITLE
Msix won't install properly

### ISSUE THREAD

**Issue by Fort-P** [MicaForEveryone/MicaForEveryone#142]
The MFE msix package won't install, as it says that it is missing a verified certificate
![image](https://user-images.githubusercontent.com/74835871/193691359-a77c6c9b-24bf-46a5-8d5a-d7fc00bc0546.png)
(I got around this by using the .exe, but you might want to investigate it)

**Comment by xmine64** [comment]
https://github.com/MicaForEveryone/MicaForEveryone/wiki/Installation#msix-file
