### ISSUE TITLE
会在第三方桌面应用外在加一个边框，很难看。

### ISSUE THREAD

**Issue by nljxlove** [MicaForEveryone/MicaForEveryone#147]
会在第三方桌面应用外在加一个边框，边框和软件主界面颜色还不一致，很难看。

DeepL translation:
> It will add a border outside the third-party desktop application, the border and the main software interface color is not consistent, it is difficult to see.

**Comment by xmine64** [comment]
We can't do anything for bugs in third-party apps, try adding a rule the affected apps to fix them.
