### ISSUE TITLE
Mica effect lost after horizontal window resize

### ISSUE THREAD

**Issue by mw88-personal** [MicaForEveryone/MicaForEveryone#151]
Whenever I resize an explorer window, or maximize/restore, the mica effect/acrylic effect/tabbed effect vanishes for the window in question permanently. The same happens, if the window is moved to another screen.

* resize is quite specific, as the bug only appears when changing the window size horizontally, i.e. by dragging left or right edge, or any corner. 
* likewise, the maximize bug only appears when using the maximize button in the top, or when double-clicking the titlebar. If just the top edge is double-clicked, the mica effect remains.

See attached screenshots for comparison.
<a href="https://user-images.githubusercontent.com/1152984/195561595-2227d10d-c6cf-47f9-be7a-f30d2a6cda5f.png">
mica apllied
<img src="https://user-images.githubusercontent.com/1152984/195561595-2227d10d-c6cf-47f9-be7a-f30d2a6cda5f.png" width="250px"/>
</a>

<a href="https://user-images.githubusercontent.com/1152984/195561606-05893318-4731-44ae-b0ef-4659ac007657.png">after window resize
<img src="https://user-images.githubusercontent.com/1152984/195561606-05893318-4731-44ae-b0ef-4659ac007657.png" width="250px"/>
</a>

**Comment by dongle-the-gadget** [comment]
I see no problems on my side.

**Comment by mw88-personal** [comment]
That's strange. On my side, the problem persists regardless of applied style. Just to be sure, these are my versions:

        Mica For Everyone 1.2.0.0
        Windows  11 (Enterprise), Version 22H2 22621.674

**Comment by xmine64** [comment]
> It says it's version 1.2.0.0 in the app, but I reinstalled it and I am sure it was the Setup from the release 1.2.0.1. It also says 1.2.0.1 in appwiz.cpl.

They're both same version just the build system is updated so i didn't bump the version.

> That's strange. On my side, the problem persists regardless of applied style.

It doesn't matter if you have this problem or not. It has nothing to do with MFE, it can be from Explorer and we can do nothing about it.

**Comment by mw88-personal** [comment]
I am sorry to bother you, and please forgive me, if I come over as rude from lack of knowledge.

I am, on the other hand, not convinced that this is not a bug on the MFE side. After all, MFE does not work as intended in my case, while every other program does work as intended. It may well be, that on my system this behaviour is due to other software and conflicts, but I feel this is a premature conclusion.

Over all, I observed unexpected behaviour with MFE, I reported it, and I provide any desired assistance, should you or any other developer decide to investigate this.

**Comment by xmine64** [comment]
> I am, on the other hand, not convinced that this is not a bug on the MFE side. 

MFE doesn't hook in to processes to render effects, the feature is already in the Windows and MFE just enables it for every window you open. It's not MFE's fault if an app changes these effects itself or an app is not getting rendered properly.

**Comment by dongle-the-gadget** [comment]
Btw, are you talking about Extending Frame Into Client Area or the Backdrop Type?

**Comment by mw88-personal** [comment]
I get this behaviour with "Extending Frame Into Client Area" toggled on and off. In the first case, the whole background is affected, in the second, only titlebar/ribbon/navigation.

Also, I have updated the links in my original report: the second link (not the thumbnail) was pointing to the wrong image.

I am looking into all my shell extensions as well, but can you clarify: Does this unexpected behaviour happen on my setup only? Or is this actually expected?

**Comment by dongle-the-gadget** [comment]
I can't say for sure. On my machine running 22623.746, File Explorer doesn't unexpectedly change the backdrop.

**Comment by mw88-personal** [comment]
I had to reinstall MFE after a windows update, and this time, I used the msixbundle installer of MFE (v1.2.0.1, same version as before). I cannot say at this point, if it was the installer, or the updated windows version (now: 22621.755), but the bug no longer persists for me.

I cannot contribute more at this point, and since it was a very rare bug/odd behaviour anyway, you may as well close this issue.

**Comment by dongle-the-gadget** [comment]
Probably the update. There is almost no difference in the MSIX compared to the portable builds except for the folder where the configuration file is stored.
