### ISSUE TITLE
Naming convention is inconsistent

### ISSUE THREAD

**Issue by Saevyn** [MicaForEveryone/MicaForEveryone#155]
It's not quite clear what this project is officially named. Although the repository and files are titled `MicaForEveryone`, [the organisation](https://github.com/MicaForEveryone) seems to be called `Mica For Everyone`, while the project's [README.md](https://github.com/MicaForEveryone/MicaForEveryone/blob/master/README.md) mentions `Mica for Everyone`. I'm not sure if this is deliberate, but it makes identifying the project's official name a bit confusing.

**Comment by dongle-the-gadget** [comment]
We can't include spaces in repository names.

**Comment by Saevyn** [comment]
It is indeed not possible to create repositories with spaces, and that's fine. I just felt like pointing this out because [another project](https://github.com/QNetITQ/WaveFox#windows-system-effects) mentions it without spaces, and I wasn't quite certain if I should correct it.

**Comment by xmine64** [comment]
"MicaForEveryone" is the project name, something we use in code. "Mica For Everyone" is the application name, we use it as title. If I wrote "Mica for Everyone" with small f in README then maybe it's because it doesn't matter too much, but I'll edit the README to make it consistent.

**Comment by Saevyn** [comment]
It probably doesn't matter much, and I apologise if I seem pedantic. I just wanted to make sure I was using the correct name in another pull request.
