### ISSUE TITLE
Enabling rounded corners causes window border to display around fullscreen apps

### ISSUE THREAD

**Issue by muno777** [MicaForEveryone/MicaForEveryone#156]
**Describe the bug**
When using the rounded corners option for a fullscreen app, the window's border can be seen at the edges of the screen, and at the bottom, the taskbar shows through also. This also happens when slightly rounded corners are enabled. This issue is not present with the square borders option, and it also is not present with Windows 11's vanilla rounded corners. Tested with Firefox (fullscreen video or just pressing F11) as well as Aseprite (pressing F11) with the same results.

**To Reproduce**
Enable rounded corners on a fullscreen app (e.g. firefox after pressing F11 or opening a fullscreen video).

**Expected behavior**

**Screenshots**
Rounded corners: (bugged behavior)
![image](https://user-images.githubusercontent.com/37985497/197597852-d5d78b15-2917-44d5-90b6-d26856fd6c3a.png)

Square corners: (desired behavior)
![image](https://user-images.githubusercontent.com/37985497/197597931-0a1d79d4-ab35-433b-ae7d-c4b6050b5fa9.png)

**Windows Version**
Windows 11 22H2

**Comment by dongle-the-gadget** [comment]
Well looks like the window corners attribute is causing it. Would be third party bug then.

**Comment by muno777** [comment]
Ah, yep - I solved it by setting the window corner option to Default instead of Rounded. It seems to require reopening the affected window (or else the bug still occurs) so maybe that's why I overlooked it before haha.

Thank you!

**Comment by dongle-the-gadget** [comment]
Yeah, Default only applies to new windows, not existing ones.

**Comment by xmine64** [comment]
Please don't report third-party issues as bug.

**Comment by dongle-the-gadget** [comment]
Could be because they don't know though.

**Comment by xmine64** [comment]
> Could be because they don't know though.

I have written it in the issue template.

**Comment by davepinto** [comment]
Sorry to continue this issue thread, but I have the same issue, where the above solution is not what I'm looking for. I installed MicaForEveryone to get rounded corners on Firefox's Picture in Picture mode. However, this means that fullscreen videos also get rounded corners in Firefox. Is there any way to get square corners/ignore styling fullscreen windows, whilst keeping rounded corners for PiP? Thanks for the great app btw.

**Comment by davepinto** [comment]
I'm back 15 minutes smarter having figured it out. Here's the solution for anyone else who wants this behavior. Create a window class rule for `MozillaDialogClass`. Give this rule the rounded corners property, then rounded corners will only be applied to the PiP mode. I'm unsure if this will have other unintended side-effects on other components that may use `MozillaDialogClass` though.

**Comment by dongle-the-gadget** [comment]
Well the answer is, we don't exactly have a really good indicator of Firefox. Generally FIrefox is a bit weird anyways.
