### ISSUE TITLE
Multiple monitor fullscreen leaves a bar on the secondary monitor

### ISSUE THREAD

**Issue by saboooor** [MicaForEveryone/MicaForEveryone#16]
idk if this makes any sense but when a window is full screen on one monitor, it shows a bar on the second monitor and vice versa
![image](https://user-images.githubusercontent.com/42164502/150526419-b3c4bf60-1094-48ce-a148-1c7004389558.png)
![image](https://user-images.githubusercontent.com/42164502/150526434-f7992a1b-fc28-4ac1-acb7-5c148b07fd48.png)
https://user-images.githubusercontent.com/42164502/150526490-15dc9683-60c7-4a3e-ae18-e5e9e6c474aa.mov

**Comment by minusium** [comment]
Hey, thanks for reporting but I think this bug is not related to Mica For Everyone. Mica For Everyone just asks DWM to draw Mica on frame of each window and doesn't do anything itself so it should be from DWM. if you see this bug only on a specific window you can config MFE to ignore that window.

**Comment by jt-github** [comment]
I have the same issue, but it could certainly be a bug with Windows 11 beta 22543.

**Comment by dongle-the-gadget** [comment]
Stale.
