### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by xmine64** [MicaForEveryone/MicaForEveryone#161]
Hi! I have added some new features and I need you to translate new strings, Thanks to all.

```xml
  <data name="AdminStartupSetting.Description" xml:space="preserve">
    <value>Run this app automatically as administrator on startup. You need to run app as Administrator to enable this option.</value>
  </data>
  <data name="AdminStartupSetting.Header" xml:space="preserve">
    <value>Run as Administrator on Startup</value>
  </data>
  <data name="ContributorsLabel.Text" xml:space="preserve">
    <value>Contributors:</value>
  </data>
  <data name="TrayIconVisibilitySetting.Description" xml:space="preserve">
    <value>Show the app icon in the notification area</value>
  </data>
  <data name="TrayIconVisibilitySetting.Header" xml:space="preserve">
    <value>Show tray icon</value>
  </data>
```

@xoascf @Danik2343 @maboroshin @uDEV2019 @alessandrocaseti @AndromedaMelody @SaiyajinK @RTFTR @krlvm 

* [x] German
* [x] Spanish
* [x] Persian
* [x] French
* [x] Italian
* [x] Japenese
* [x] Korean
* [x] Russian
* [x] Simplified Chinese
* [x] Traditional Chinese

**Comment by krlvm** [comment]
Russian

```xml
  <data name="AdminStartupSetting.Description" xml:space="preserve">
    <value>Запускать приложениепри запуске системы, требуются права администратора</value>
  </data>
  <data name="AdminStartupSetting.Header" xml:space="preserve">
    <value>Запускать программу при запуске системы от имени администратора</value>
  </data>
  <data name="ContributorsLabel.Text" xml:space="preserve">
    <value>Контрибьюторы:</value>
  </data>
  <data name="TrayIconVisibilitySetting.Description" xml:space="preserve">
    <value>Отображать значок приложения в области уведомлений</value>
  </data>
  <data name="TrayIconVisibilitySetting.Header" xml:space="preserve">
    <value>Отображать значок в трее</value>
  </data>
```

**Comment by uDEV2019** [comment]
added in PR #158

**Comment by Danik2343** [comment]
PR #162

**Comment by AndromedaMelody** [comment]
```
  <data name="AdminStartupSetting.Description" xml:space="preserve">
    <value>始终以管理员身份运行此应用。你需要管理员权限来启用此选项。</value>
  </data>
  <data name="AdminStartupSetting.Header" xml:space="preserve">
    <value>始终以管理员身份运行</value>
  </data>
  <data name="ContributorsLabel.Text" xml:space="preserve">
    <value>参与贡献：感谢</value>
  </data>
  <data name="TrayIconVisibilitySetting.Description" xml:space="preserve">
    <value>在任务栏通知区域显示图标</value>
  </data>
  <data name="TrayIconVisibilitySetting.Header" xml:space="preserve">
    <value>显示托盘图标</value>
  </data>
```

'Tabbed' has had official name 'Mica Alt', I think this name need keep pace with [Microsoft Learn](https://learn.microsoft.com/en-us/windows/apps/design/style/mica#app-layering-with-mica-alt).

**Comment by RTFTR** [comment]
`  <data name="AdminStartupSetting.Description" xml:space="preserve">
    <value>컴퓨터 시작 후에 관리자 권한으로 자동 실행하기 (이 설정을 활성화 시키려면 이 앱을 관리자 권한으로 실행하셔야 합니다.)</value>
  </data>
  <data name="AdminStartupSetting.Header" xml:space="preserve">
    <value>컴퓨터 시작 후에 이 애블 관리자 권한으로 자동 실행하기</value>
  </data>
  <data name="ContributorsLabel.Text" xml:space="preserve">
    <value>이 앱에 기여한 사람들:</value>
  </data>
  <data name="TrayIconVisibilitySetting.Description" xml:space="preserve">
    <value>알림 구역에 이 앱 아이콘 표시하기/value>
  </data>
  <data name="TrayIconVisibilitySetting.Header" xml:space="preserve">
    <value>시스템 트레이에 이 앱 아이콘 표시하기</value>
  </data>`

**Comment by RTFTR** [comment]
` <data name="AdminStartupSetting.Description" xml:space="preserve">
    <value>컴퓨터 시작 후에 관리자 권한으로 자동 실행하기 (이 설정을 활성화 시키려면 이 앱을 관리자 권한으로 실행하셔야 합니다.)</value>
  </data>
  <data name="AdminStartupSetting.Header" xml:space="preserve">
    <value>컴퓨터 시작 후에 이 애블 관리자 권한으로 자동 실행하기</value>
  </data>
  <data name="ContributorsLabel.Text" xml:space="preserve">
    <value>이 앱에 기여한 사람들:</value>
  </data>
  <data name="TrayIconVisibilitySetting.Description" xml:space="preserve">
    <value>알림 구역에 이 앱 아이콘 표시하기/value>
  </data>
  <data name="TrayIconVisibilitySetting.Header" xml:space="preserve">
    <value>시스템 트레이에 이 앱 아이콘 표시하기</value>
  </data>`

**Comment by RTFTR** [comment]
[d.txt](https://github.com/MicaForEveryone/MicaForEveryone/files/9945913/d.txt)

I don't know how to write codes like that, So i am uploading txt file instead, sorry.

**Comment by RTFTR** [comment]
```  <data name="AdminStartupSetting.Description" xml:space="preserve">
    <value>컴퓨터 시작 후에 관리자 권한으로 자동 실행하기 (이 설정을 활성화 시키려면 이 앱을 관리자 권한으로 실행하셔야 합니다.)</value>
  </data>
  <data name="AdminStartupSetting.Header" xml:space="preserve">
    <value>컴퓨터 시작 후에 이 애블 관리자 권한으로 자동 실행하기</value>
  </data>
  <data name="ContributorsLabel.Text" xml:space="preserve">
    <value>이 앱에 기여한 사람들:</value>
  </data>
  <data name="TrayIconVisibilitySetting.Description" xml:space="preserve">
    <value>알림 구역에 이 앱 아이콘 표시하기/value>
  </data>
  <data name="TrayIconVisibilitySetting.Header" xml:space="preserve">
    <value>시스템 트레이에 이 앱 아이콘 표시하기</value>
  </data>```

**Comment by RTFTR** [comment]
```
  <data name="AdminStartupSetting.Description" xml:space="preserve">
    <value>컴퓨터 시작 후에 관리자 권한으로 자동 실행하기 (이 설정을 활성화 시키려면 이 앱을 관리자 권한으로 실행하셔야 합니다.)</value>
  </data>
  <data name="AdminStartupSetting.Header" xml:space="preserve">
    <value>컴퓨터 시작 후에 이 애블 관리자 권한으로 자동 실행하기</value>
  </data>
  <data name="ContributorsLabel.Text" xml:space="preserve">
    <value>이 앱에 기여한 사람들:</value>
  </data>
  <data name="TrayIconVisibilitySetting.Description" xml:space="preserve">
    <value>알림 구역에 이 앱 아이콘 표시하기/value>
  </data>
  <data name="TrayIconVisibilitySetting.Header" xml:space="preserve">
    <value>시스템 트레이에 이 앱 아이콘 표시하기</value>
  </data>```

**Comment by RTFTR** [comment]
#171 Added, If you found something, Contact me again

**Comment by xoascf** [comment]
Installed Windows 11 just to test my translation 😅

Unfortunately, it crashes immediately, regardless of whether I am using a local build or the [CI one](https://github.com/MicaForEveryone/MicaForEveryone/actions/workflows/ci.yml):

![UnhandledExceptionMicaForEveryone](https://user-images.githubusercontent.com/28744392/200223415-e33e2913-1ca2-451e-952e-7f01f111341a.png)

**Comment by xmine64** [comment]
> Unfortunately, it crashes immediately

I've seen it before in #56, I have to fix it. It works on my machine but others have this problem.
I guess you can fix it by setting `HKCU\Software\MicaForEveryone\tray icon visibility` to `True` manually.

**Comment by SaiyajinK** [comment]
Hi,

sorry for the delay, I had a lot of work on my side.

*french translation :*

 <data name="AdminStartupSetting.Description" xml:space="preserve">
    <value>Exécutez cette application automatiquement en tant
qu'administrateur au démarrage. Vous devez exécuter l'application en tant
qu'administrateur pour activer cette option.</value>
  </data>
  <data name="AdminStartupSetting.Header" xml:space="preserve">
    <value>Exécuter en tant qu'administrateur au démarrage</value>
  </data>
  <data name="ContributorsLabel.Text" xml:space="preserve">
    <value>Contributeurs:</value>
  </data>
  <data name="TrayIconVisibilitySetting.Description" xml:space="preserve">
    <value>Afficher l'icône de l'application dans la zone de
notification</value>
  </data>
  <data name="TrayIconVisibilitySetting.Header" xml:space="preserve">
    <value>Afficher l'icône dans la barre des tâches</value>
  </data>

see you ++


Le sam. 29 oct. 2022 à 19:55, Mohammad Amin ***@***.***> a
écrit :

**Comment by xmine64** [comment]
You have to set it to `True` not `true`

**Comment by xoascf** [comment]
> You have to set it to `True` not `true`

Still the same even on W10:
![imagen](https://user-images.githubusercontent.com/28744392/200653108-31fad8b2-f5c9-4445-b65c-97c9710b19ba.png)

Hint: Check the error log, it says SetValue (value to set cannot be null.)

**Comment by xmine64** [comment]
I already know what's wrong, I'll fix it as soon as I can.

**Comment by xmine64** [comment]
@SaiyajinK @alessandrocaseti I will remove French and Italian translations if you don't update it until next week.

**Comment by SaiyajinK** [comment]
> @SaiyajinK @alessandrocasetiJe supprimerai les traductions française et italienne si vous ne les mettez pas à jour avant la semaine prochaine.
Hi,

I posted the translation below in November following receipt of your request (upper)

----------

*french translation :*

```
 <data name="AdminStartupSetting.Description" xml:space="preserve">
    <value>Exécutez cette application automatiquement en tant
qu'administrateur au démarrage. Vous devez exécuter l'application en tant
qu'administrateur pour activer cette option.</value>
  </data>
  <data name="AdminStartupSetting.Header" xml:space="preserve">
    <value>Exécuter en tant qu'administrateur au démarrage</value>
  </data>
  <data name="ContributorsLabel.Text" xml:space="preserve">
    <value>Contributeurs:</value>
  </data>
  <data name="TrayIconVisibilitySetting.Description" xml:space="preserve">
    <value>Afficher l'icône de l'application dans la zone de
notification</value>
  </data>
  <data name="TrayIconVisibilitySetting.Header" xml:space="preserve">
    <value>Afficher l'icône dans la barre des tâches</value>
  </data>
```

**Comment by xmine64** [comment]
> I posted the translation below in November following receipt of your request (upper)

Sorry I didn't see that, Thanks you!
