### ISSUE TITLE
Add aero glass to MicaForEveryone

### ISSUE THREAD

**Issue by 3060PlayZ-github** [MicaForEveryone/MicaForEveryone#163]
**Describe the solution you'd like**
Add aero glass to MicaForEveryone, when slowed down it looks like it has aero for a split second (in the screenshot).
Basically, add the Windows 7 transperent glass to MicaForEveryone. 

**Describe alternatives you've considered**
AeroGlass for Win 8.1, but it didn't work.

**Additional context**
in slow motion:
![Adobe_Premiere_Pro_zt7uR2f1Vu](https://user-images.githubusercontent.com/80703247/199064650-9a6ef273-8013-4c15-97a6-a922521e9a5c.png)

**Comment by xmine64** [comment]
It's not possible, Mica For Everyone only asks Desktop Window Manager to render requested backdrop. It doesn't do anything for rendering itself so effects that are not available in the Windows itself won't be possible. AeroGlass project hooks into running apps and renders the glass itself, MFE doesn't.
