### ISSUE TITLE
Random Gray Box Overlays Desktop

### ISSUE THREAD

**Issue by LovelyLince** [MicaForEveryone/MicaForEveryone#167]
Big gray box overlays the desktop icons & wallpaper whenever I open the notification panel or system apps like control panel. The box disappears after a few minutes but will reappear if you open the previously mentioned items. Uninstalling MicaForEveryone & rebooting my PC removes the box, so it doesn't seem to be an issue with Windows itself or other 3rd-party apps.

![2022-11-03](https://user-images.githubusercontent.com/104088953/199677793-5209a209-be28-49c7-9ba8-569585db1677.png)

**Windows Version**
Windows 11 Pro N Build 22621

**Comment by xmine64** [comment]
> Uninstalling MicaForEveryone & rebooting my PC removes the box, so it doesn't seem to be an issue with Windows itself or other 3rd-party apps.

It's not like that, you have an open app that creates an invisible window, when you run MFE it asks Windows to render an effect for that invisible window so you see it as a gray box.

You should find what app is it then create a rule for it in MFE. You can use various tools to find that, like inspect from Windows SDK.

**Comment by dongle-the-gadget** [comment]
I personally use Spy++. Use the window finder to open the properties window, go to the Process tab and click on the Process ID to get the app that creates that window (or just use the window class).

Btw they also mentioned that system apps are affected by this. Probably something to look into? On my machine MFE-CPP doesn't have this issue. Haven't tested for MFE-C# though.

**Comment by xmine64** [comment]
> they also mentioned that system apps are affected by this.

Idk I don't have this problem, but maybe we should add a rule for it to the default config file.

**Comment by LovelyLince** [comment]
The issue lied with a third-party app I had running in the background (ScpTrayApp); so I excluded it, & my issue was fixed. System apps aren't part of the issue, but it's interesting how opening them causes ScpTrayApp to open. Anyway, sorry for the trouble.

**Comment by JaneValleyhasBtaken** [comment]
I was also getting this grey box as it covered my entire screen (includes taskbar) when I run it. Really not sure which APP has caused it.

**Comment by dongle-the-gadget** [comment]
> I was also getting this grey box as it covered my entire screen (includes taskbar) when I run it. Really not sure which APP has caused it.

Probably a third-party bug. Can you file a separate issue?

**Comment by JaneValleyhasBtaken** [comment]
Yes I can, but I don't think I can provide anything useful information (like Logs) other than this description

**Comment by dongle-the-gadget** [comment]
I'll help you out in a separate issue. Please don't send offtopic messages.
