### ISSUE TITLE
Mica background doesn't apply consistently 

### ISSUE THREAD

**Issue by SlavBoi420** [MicaForEveryone/MicaForEveryone#168]
**Description**
I tried using MFE on explorer, and it is very finnicky when it comes to actually applying the background. It works a lot better in 22H2 and the background is very nice (when it actually works), but most of the time, when I open explorer, the background simply doesn't apply. And at times when the background actually applies, it goes away again after closing the app. 

I have set Extend Frame to Client Area on.

What is weirder is that the text doesn't become white in any of the windows either, when it works, it works perfectly. Just that it doesn't work most of the time.

**Target Application**
File Explorer

**To Reproduce**
I don't think there is any real way to reproduce this, it just randomly happens when I open and close the explorer. Sometimes, the background gets applied, other times, it is the same plain black background that appears in Windows 11.

All this happened on Windows 11 22H2 (Build 22621.755) and MicaForEveryone v1.2.0.0

**Comment by dongle-the-gadget** [comment]
Explorer is very finicky when it comes to Extend Frame Into Client Area. Fixing this problem will require process hooking. I have an idea for using Detours and DLL hooking to resolve this, but currently can't quite execute on it yet.

**Comment by SlavBoi420** [comment]
I kinda found this weird observation that it works a lot more frequently if we have a UWP app open in the background, but I can't really say if this behaviour happens all the time

**Comment by dongle-the-gadget** [comment]
Well finally managed to have a prototype: https://github.com/MicaForEveryone/ExplorerFrame.

**Comment by SlavBoi420** [comment]
Woah, this thing is absolutely sick! This is exactly what I wanted with the Windows 11 File Explorer in the first place (aside from tabs, which we have right now). Amazing job right there, and thank you for your help :)
