### ISSUE TITLE
App doesn't recognize .NET Core

### ISSUE THREAD

**Issue by jadelily18** [MicaForEveryone/MicaForEveryone#177]
**Describe the bug**
App only launches with the following error:
```
To run this application, you must install .NET Core.
Would you like to download it now?
```

When I click yes, it does nothing. I've tried manually installing .NET 6 from [here](), but it does the same thing.

**To Reproduce**
Launch MicaForEveryone.

**Expected behavior**
MicaForEveryone should open.

**Screenshots**
![image](https://user-images.githubusercontent.com/74706690/201503398-c0cb4ec6-9ab8-4c8d-be8f-3ef04f00f2a1.png)

**Windows Version**
Windows 11 Pro Version 22H2 (OS Build 22621.819)

**Additional context**
N/A

**Comment by dongle-the-gadget** [comment]
It needs .NET Core 3.1, not .NET 6.

**Comment by jadelily18** [comment]
> It needs .NET Core 3.1, not .NET 6.
oh god i feel so dumb thank you

**Comment by Woisol** [comment]
So strange it is that a newer version is not supported …

**Comment by bigplayer-ai** [comment]
Hey,
can you add that the app needs .net core 3.1 in its github description?

**Comment by dongle-the-gadget** [comment]
It's in the Wiki, I believe.

**Comment by wordscode** [comment]
Developers should add it to the Readme, which saves many people time
https://dotnet.microsoft.com/zh-cn/download/dotnet/3.1

**Comment by dongle-the-gadget** [comment]
I've told that it is in the Wiki.
