### ISSUE TITLE
Error Path String Empty

### ISSUE THREAD

**Issue by Santorr321** [MicaForEveryone/MicaForEveryone#180]
**Describe the bug**
I install de app and when executing this error comes out

**To Reproduce**
Start de app 

**Expected behavior**
Open the app

**Screenshots**
![image](https://user-images.githubusercontent.com/105893768/201531532-27b1fbd4-fe5a-4620-8513-dc999a85f2ad.png)

**Windows Version**
 Windows 10 build 19045

**Comment by dongle-the-gadget** [comment]
Did you change the default file path in any way?

**Comment by Santorr321** [comment]
I don't remember

**Comment by dongle-the-gadget** [comment]
Maybe check `config file path` in `HKCU\Software\MicaForEveryone"`?

**Comment by Santorr321** [comment]
I already solved it, but now the application does not load properly

![image](https://user-images.githubusercontent.com/105893768/201533173-7da608b7-cab3-4002-b8a2-605ea5e3ba11.png)

**Comment by Santorr321** [comment]
And it does not allow to change, only default appears

![image](https://user-images.githubusercontent.com/105893768/201533398-fc72c834-dc71-488f-b61f-33149e48f131.png)

**Comment by xmine64** [comment]
Windows 10 is not fully supported, check #65

**Comment by xmine64** [comment]
This should be fixed in the latest version. I close this.
