### ISSUE TITLE
Unable to apply settings in 22H2 APPs

### ISSUE THREAD

**Issue by Amartoros** [MicaForEveryone/MicaForEveryone#182]
**Describe the bug**
Blur settings won't be applyed to new explorer window and Office 365.

**To Reproduce**
Start the app and do as the screenshot shows

**Screenshots**
Settings like this:
![a](https://user-images.githubusercontent.com/117239896/201833881-06bbe6b1-12b9-49e3-8b95-31ed02881dbc.png)
![UZVW37HM9FG2G@N90DT)XHN](https://user-images.githubusercontent.com/117239896/201834037-9d8573ac-d9d2-42ce-8a48-54fd10de1917.png)

Shows on the interfaces and (example) Excel 365:
![b](https://user-images.githubusercontent.com/117239896/201833963-8e0eb9f6-fe9a-4f95-a12c-5cfc369af868.png)
![HZJ~)%LM6GJK_4$OH6U I08](https://user-images.githubusercontent.com/117239896/201834195-bee13cd0-87cc-4895-9adb-2898744521b2.png)
![T7J%SZOFL1Y7RWBIG7IET}9](https://user-images.githubusercontent.com/117239896/201834127-c88224e9-95a9-4f3a-9469-b1eaa0926322.png)

**Windows Version**
Windows 11 22H2 22621.819

**Comment by dongle-the-gadget** [comment]
Extend Frame Into Client Area is known to break Explorer. Office has their own Mica implementation (probably relies on Composition), so it isn't affected by Mica For Everyone.

**Comment by Amartoros** [comment]
> Extend Frame Into Client Area is known to break Explorer in Light mode (in Dark mode it will revert to a solid background if you resize of change its activation status). Office has their own Mica implementation (probably relies on Composition), so it isn't affected by Mica For Everyone.

Will it be fixed in the future? (Not saying Office)

**Comment by dongle-the-gadget** [comment]
Unfortunately, this bug is outside of Mica For Everyone control (hence the third-party tag).

**Comment by dongle-the-gadget** [comment]
Actually you could somewhat mitigate the problem with Dark Explorer using https://github.com/MicaForEveryone/ExplorerFrame, but this wouldn't work on the Properties window.
