### ISSUE TITLE
Not global acrylic

### ISSUE THREAD

**Issue by Jack253-png** [MicaForEveryone/MicaForEveryone#191]
**Describe the bug**
MMC Window is not modified.

**To Reproduce**
null

**Expected behavior**
null

**Screenshots**
![image](https://user-images.githubusercontent.com/83895170/205433249-9685a6c4-3caa-4bfc-90db-a3b6c02da3d4.png)

**Windows Version**
Windows 11 22H2 22621.819

**Additional context**
null

**Comment by Jack253-png** [comment]
![image](https://user-images.githubusercontent.com/83895170/205438806-98206dd6-ae3a-48fc-a661-f3838e85fc22.png)
also task manager

**Comment by dongle-the-gadget** [comment]
Restart MFE as admin. This is a security boundary enforced by Windows.

**Comment by Jack253-png** [comment]
But I selected the option with administrator icon when i am installing MFE.And it didn't open the UAC Window and MFE can't run as administrator when the computer startup.I must add the computer startup program by my self.Is this a installer bug?
