### ISSUE TITLE
Requires install .net but I have it from 3.5 to 7.0

### ISSUE THREAD

**Issue by 111ebobo** [MicaForEveryone/MicaForEveryone#194]
Windows 11 22621.900

**Comment by fewp** [comment]
I'm facing the same problem, Windows 11 version 22H2, build 22621.819

**Comment by fyn130** [comment]
I had the same problem, did you solve it?

**Comment by yyyyyyounger** [comment]
Try this way. 
https://github.com/MicaForEveryone/MicaForEveryone/issues/177#issuecomment-1312628212
It helps me. 

.Net Core 3.1 download:
https://dotnet.microsoft.com/en-us/download/dotnet/3.1

**Comment by xmine64** [comment]
Duplicate, and not a bug.

**Comment by 111ebobo** [comment]
> I had the same problem, did you solve it?

Yes, you need a 3.0
