### ISSUE TITLE
Icons on MFE not shown correctly - just squares. 

### ISSUE THREAD

**Issue by UnclWish** [MicaForEveryone/MicaForEveryone#197]
Windows 10 19045 icons on gui:
![image](https://user-images.githubusercontent.com/17703902/206101164-2a11a5c4-7811-488f-b073-2d6809772080.png)

Maybe need some special font?

**Comment by xmine64** [comment]
Windows 10 support is limited, see #65.

**Comment by xmine64** [comment]
I close this as we already have #65. For fixing this we just need to embed Segoe Fluent Icons in the app. You can install it manually too.
