### ISSUE TITLE
Terminal gray box bug is back

### ISSUE THREAD

**Issue by KrazyLurt** [MicaForEveryone/MicaForEveryone#202]
**Describe the bug**
The Terminal gray box bug is back, cant be solved with adding OpenConsole

**To Reproduce**
1. Open Terminal w MFE enabled
2. observe gray box top left corner

**Windows Version**
Windows 11 build 22621.963 (stable)

**Comment by PhoenixCODE2322** [comment]
yes happening with me too , i created the issue on `Windowstermnal` github  , should i close it ? 
i also tried adding OpenConsole and Windows Termial but no help.

**Comment by KrazyLurt** [comment]
Yeah looking at the Windows Terminal repo on Github, it got updated to v1.15.3466.0 (Windows 11) , I'm quite sure this version brought back the grey box.

**Comment by dongle-the-gadget** [comment]
I saw it at the bottom right. I'll backport a newer window check from an internal version and see if that works.

**Comment by dongle-the-gadget** [comment]
Can you download the artifacts of the above commit (you can reach there by clicking on the tick icon) and see if it fixes the problem?

**Comment by KrazyLurt** [comment]
> Can you download the [artifacts](https://github.com/MicaForEveryone/MicaForEveryone/actions/runs/3715081210) (you may need to scroll down to see them) of the above commit and see if it fixes the problem?

Works beautifully, awesome job buddy!
Seems like this fixes #176 as well, probably expected as the fix (as far as I understand) improves the window exclusion check.

**Comment by PhoenixCODE2322** [comment]
This fixed the issue , thank you.

**Comment by dongle-the-gadget** [comment]
Fix released in 1.3 preview, closing.
