### ISSUE TITLE
Inactive explorer window turns black

### ISSUE THREAD

**Issue by x-0D** [MicaForEveryone/MicaForEveryone#203]
Windows 11 Build 25267.rs_prerelease.221209-1557

![image](https://user-images.githubusercontent.com/87000516/208163704-5df6c3b0-ecd7-41d1-8782-7e031d4f94cb.png)
Inactive explorer window turns black

![image](https://user-images.githubusercontent.com/87000516/208164349-6e3781bc-e320-423f-8866-0b0707a56342.png)
explorer windows saves it's colors when at least one explorer window keeps active

![image](https://user-images.githubusercontent.com/87000516/208164024-ab433521-6545-4e27-aeee-2c40e4f4fbf1.png)
Inactive explorer window saves normal color, but last inactive window turns black

Analogical Issue is opened in [Rectify11Installer](https://github.com/MishaTY/Rectify11Installer/issues/67) Repository

**Comment by dongle-the-gadget** [comment]
Closed on corresponding repository.
