### ISSUE TITLE
Need root cedrtificate to install msix

### ISSUE THREAD

**Issue by LegzRwheelz** [MicaForEveryone/MicaForEveryone#204]
**Describe the bug**
I cannot install the msix variant by double clicking or via PS. 

**To Reproduce**
1. Double click on app and receive the error 
or
attempt installation via powershell using Add-AppxPackage and then the path to the app
3. See error(s)

**Expected behavior**
To install

**Screenshots**
![Screenshot 2022-12-16 212915](https://user-images.githubusercontent.com/56568943/208226977-07f46983-9334-4e92-a7f1-3a73c08e608c.png)
![Screenshot 2022-12-16 213007](https://user-images.githubusercontent.com/56568943/208226979-2f087f2c-426c-47c3-aaa6-588fd7d73a3b.png)

**Windows Version**
E.g. Windows 11 build 22621.963

**Comment by dongle-the-gadget** [comment]
[Read the manual please](https://github.com/MicaForEveryone/MicaForEveryone/wiki/Installation#msix-file)
