### ISSUE TITLE
The new version of Snipping Tool's recording function will have an abnormal gray screen when the software is enabled.

### ISSUE THREAD

**Issue by WhatDamon** [MicaForEveryone/MicaForEveryone#205]
**Describe the bug**
The new version of Snipping Tool's recording function will have an abnormal gray screen when this software is enabled, resulting in the inability to properly record video of the selected area, and the gray screen will partially obscure the recorded content!

**Rule**
```
Global {
  TitleBarColor             = System  # available modes: Default, System, Light, Dark (case sensitive)
  BackdropPreference        = Acrylic    # available modes: Default, None, Mica, Acrylic, Tabbed
  CornerPreference          = Default # available modes: Default, Square, Rounded, RoundedSmall
  ExtendFrameIntoClientArea = False   # enable to apply backdrop on background of apps (not recommended)
  EnableBlurBehind          = False   # make window translucent (not recommended)
}
```
No rules set specifically for Snipping Tool

**Target Application**
- App: Snipping Tool(截图工具)
- Version: 11.2211.35.0

**To Reproduce**
1. Open Snipping Tool
2. Click "Record" and "New"
3. Frame the recorded content
4. See the bug

**Expected behavior**
The selected area becomes gray.
But the recording is fine.

**Screenshots**
![BUG](https://user-images.githubusercontent.com/59256766/208256882-a8f4bd11-c65c-4516-930b-5fadf37ed903.jpg)
I can't SCREENSHOT or RECORD this stuff！
But I can phone shoot this stuff  ; )

**Windows Version**
Windows 11 Dev Build 25267

**Additional context**
(Using machine translation, the translated content may differ from the actual meaning)

**Comment by dongle-the-gadget** [comment]
It would be hard to implement an exclusion check for this.

**Comment by dongle-the-gadget** [comment]
The recording area might have been fixed as part of b7e337030fc567ea392f34534ed843ef1f8ffaf2, but the toolbar isn't fixed.

**Comment by SmirbYrneh420** [comment]
The recording area is still dead, but it seems to record properly.

https://user-images.githubusercontent.com/110212580/216722835-da4b4ce1-4bee-4c1b-ad76-8f8eb6387407.mp4


![IMG_1442](https://user-images.githubusercontent.com/110212580/216723150-3f45179f-df94-461a-aa56-5c5e0c837721.jpg)

**Comment by SmirbYrneh420** [comment]
(Excuse the abnormally smol taskbar; I used Windhawk to do that and has nothing to do with this.)

**Comment by SmirbYrneh420** [comment]
(Excuse the abnormally smol taskbar; I used Windhawk to do that and it has nothing to do with this.)

**Comment by itzbluebxrry** [comment]
Set a rule for `ScreenSketch` and set the Backdrop Material to "None"

**Comment by xmine64** [comment]
> set the Backdrop Material to "None"

Prefer using Default, you may need to restart the affected app but setting Default won't touch the target app while None disables the backdrop if the app is using any.

**Comment by SmirbYrneh420** [comment]
Ok, maybe not for process ScreenSketch, but for process SnippingTool it works
Default doesn't fix the issue

**Comment by itzbluebxrry** [comment]
> > set the Backdrop Material to "None"
> 
> Prefer using Default, you may need to restart the affected app but setting Default won't touch the target app while None disables the backdrop if the app is using any.

Eh won't Default will make it use the Global settings?

**Comment by xmine64** [comment]
> won't Default will make it use the Global settings?

I didn't think about it that way, maybe we should use another name that's more clear.

**Comment by SmirbYrneh420** [comment]
Default does not fix the gray cover
Setting it to None fixes it

Now I need to complain that IT DOESN'T RECORD AUDIO

**Comment by xmine64** [comment]
> Default does not fix the gray cover
Setting it to None fixes it

Default does it, but you need to kill snipping tool from task manager and restart it.

> Now I need to complain that IT DOESN'T RECORD AUDIO

That's not my problem, you have to ask it some where else.

**Comment by SmirbYrneh420** [comment]
(yes ik that is microsoft issue but still...)

**Comment by xmine64** [comment]
> (yes ik that is microsoft issue but still...)

You talk like I broke your computer. I don't have any responsibility.

**Comment by SmirbYrneh420** [comment]
sorry for my weird tone
