### ISSUE TITLE
Oops on... directory?

### ISSUE THREAD

**Issue by Peter20130402** [MicaForEveryone/MicaForEveryone#206]
a few years ago, I downloaded MFE, but when I changed the directory for settings, it always crashes. I tried reinstalling it, but still doesn't work. Any way to fix it?
Error message:
![image](https://user-images.githubusercontent.com/110669701/209107357-71192600-6705-4226-8a1e-8527f14afee8.png)
![image](https://user-images.githubusercontent.com/110669701/209107444-8c7cf223-097c-4d47-ba25-bd8229add30e.png)
![image](https://user-images.githubusercontent.com/110669701/209107508-b3c67512-587e-452d-b7ad-b6c347f3620a.png)

**Comment by dongle-the-gadget** [comment]
Can you actually read and write to the file?

**Comment by Peter20130402** [comment]
what do you mean

**Comment by Peter20130402** [comment]
> Can you actually read and write to the file?

what do you mean

**Comment by Peter20130402** [comment]
> > Can you actually read and write to the file?
> 
> what do you mean

which file

**Comment by dongle-the-gadget** [comment]
Did you specify a file or a directory? It kinda seems like you specified a directory.

**Comment by Peter20130402** [comment]
Uhh i cant make a file there

**Comment by Peter20130402** [comment]
and how do I reset it

**Comment by dongle-the-gadget** [comment]
If I remember correctly, delete everything in HKEY_CURRENT_USER\Software\MicaForEveryone (or Mica For Everyone? Idk).

To be rather honest, I prefer using MSIX.

**Comment by Peter20130402** [comment]
whats msix

**Comment by dongle-the-gadget** [comment]
It’s an installing tech.

**Comment by Peter20130402** [comment]
oh how do i install taht

**Comment by dongle-the-gadget** [comment]
Actually you can just revert anything using registry I like told you above. Installing using MSIX is a bit more involved currently.

**Comment by Peter20130402** [comment]
ok its working now thanks
