### ISSUE TITLE
If the program is run as an administrator, the "window corners" setting of Mica will not take effect.

### ISSUE THREAD

**Issue by SiaYung** [MicaForEveryone/MicaForEveryone#211]
**Describe the bug**
If the program is run as an administrator, the "window corners" setting of Mica will not take effect.

**Screenshots**

![Clip_20221225_111930](https://user-images.githubusercontent.com/11502551/209455956-5d7713ad-dce5-4092-bbe5-266e515385e2.png)
![Clip_20221225_112017](https://user-images.githubusercontent.com/11502551/209455965-cc4874df-68c5-43e2-8e4b-1bc68b8a131a.png)

**Windows Version**
 Windows 11 Build 22621.963 Windows 专业工作站版

Thanks！！

**Comment by dongle-the-gadget** [comment]
This is due a Windows security limitation. A workaround is to launch MFE in admin.

**Comment by SiaYung** [comment]
> This is due a Windows security limitation. A workaround is to launch MFE in admin.

问题已经解决，谢谢您的回复！
