### ISSUE TITLE
Running as admin on startup not working

### ISSUE THREAD

**Issue by sysven32** [MicaForEveryone/MicaForEveryone#212]
**Describe the bug**
MicaForEveryone isn't launching as admin on logon.

**To Reproduce**
1. Launch MFE as admin
2. Enable `Run as Administrator on Startup`
3. Log out & log back in

**Expected behavior**
MicaForEveryone should be launched as admin on startup.

**Screenshots**
![image](https://user-images.githubusercontent.com/63135654/209472535-37593ab0-35a3-4712-b28e-6a7a2ecdac4d.png)

**Windows Version**
Windows 11 22H2

**Additional context**
I opened Task Scheduler to see what's wrong, it turns out the task is attempting to launch MFE with a DLL file.
Shouldn't it be running `MicaForEveryone.exe`?

**Comment by xmine64** [comment]
> I opened Task Scheduler to see what's wrong, it turns out the task is attempting to launch MFE with a DLL file.
Shouldn't it be running MicaForEveryone.exe?

Yes it should be MicaForEveryone.exe, something should be wrong. Thanks for reporting it I'll investigate it!
