### ISSUE TITLE
Add support for Amoled / Black titlebars

### ISSUE THREAD

**Issue by DeGamersSpelen** [MicaForEveryone/MicaForEveryone#215]
Title.

**Comment by dongle-the-gadget** [comment]
I believe immersive dark mode already did this?

**Comment by DeGamersSpelen** [comment]
What is immersive dark mode? Can't find anything about it anywhere.

**Comment by dongle-the-gadget** [comment]
It's a DWM flag, which is implemented in Mica For Everyone in the Title Bar Color setting.

**Comment by DeGamersSpelen** [comment]
Yep just realized when I typed TitleBarColor = "000000" in the config file.
Thanks!

**Comment by dongle-the-gadget** [comment]
I believe MFE should just throw an error if you try to do that?
