### ISSUE TITLE
Rule is not applied to new windows opened by X410

### ISSUE THREAD

**Issue by sergiirepin** [MicaForEveryone/MicaForEveryone#216]
**Describe the bug**
I run WSL2 Ubuntu applications via x410 in `Windowed Apps` mode.
Ubuntu application is started in x410 window and has Light titlebar which is not correct.
But if I run `reload rules`  the titlebar is updated.

**Rule**
Global rule

**Target Application**
- x410

**Expected behavior**
Titlebar of x410 window has correct color on start and not only after reloading rules.

**Screenshots**

**Windows Version**
Windows 11 Pro 21H2 22000.1335

**Additional context**

**Comment by dongle-the-gadget** [comment]
Can you please attach a screenshot?

**Comment by sergiirepin** [comment]
@dongle-the-gadget 

On screenshot it looks like normal application.
This is how it looks after start
![image](https://user-images.githubusercontent.com/3786058/209946891-5bbb1bb4-a189-4c07-adb1-257a119d4299.png)

And after reloading config it looks like 
![image](https://user-images.githubusercontent.com/3786058/209946966-b58c6db7-a285-4159-a1ca-23604ba6d307.png)

**Comment by dongle-the-gadget** [comment]
I think this is due to a timing bug where WSL sets the attribute way later than window creation.
Not much we can do if that's the case.

**Comment by sergiirepin** [comment]
@dongle-the-gadget 
So WSL reset the attribute in the end ?
Is it possible to add optional timeout for the rule as a workaround ?

**Comment by xmine64** [comment]
> I think this is due to a timing bug where WSL sets the attribute way later than window creation.

We need something to capture events for showing window.

**Comment by xmine64** [comment]
@dongle-the-gadget I installed X410 to test and guess what? `RuleService.WinEvent_Handler` is not getting called at all.

**Comment by sergiirepin** [comment]
@xmine64 Is there a chance to fix this, I mean can it be fixed potentially ?

**Comment by xmine64** [comment]
> Is there a chance to fix this, I mean can it be fixed potentially ?

I don't know what's happening, I'm trying to figure it out. It's a weird bug.

**Comment by xmine64** [comment]
That didn't fix the issue🙂 We really need some delay, not because X410 resets attribute but because X410 windows are not considered as a valid window by MFE at the exact moment that they are created. They need some time.

**Comment by xmine64** [comment]
This time fixed for real

**Comment by dongle-the-gadget** [comment]
Showing window doesn't work for Firefox though. Firefox only applies attributes after initialization, but the window could be shown moments before that.

**Comment by dongle-the-gadget** [comment]
Also make sure the timer runs in a separate thread, since otherwise you will just cause the UI to hang, which is very VERY bad.

**Comment by dongle-the-gadget** [comment]
Maybe we should create a new thread for every window, so the effects can be applied in parallel?

**Comment by xmine64** [comment]
> Also make sure the timer runs in a separate thread, since otherwise you will just cause the UI to hang, which is very VERY bad.

WinEvent callbacks are called in the UI thread? I thought they're running in a different thread. You're right I should create another thread for them.

**Comment by dongle-the-gadget** [comment]
No idea actually :)

**Comment by xmine64** [comment]
> Showing window doesn't work for Firefox though.

Well I tested with glxgears. It wasn't working at first but after adding that it worked. @sergiirepin Could you test if it works on Firefox?

**Comment by sergiirepin** [comment]
@xmine64 How to get the updates ?

**Comment by dongle-the-gadget** [comment]
You currently need to go to Actions > latest CI run > scroll down and download the files there.

**Comment by sergiirepin** [comment]
The Firefox was an example. 
I use it mostly for PhpStorm. 
But the behavior is the same.

**Comment by sergiirepin** [comment]
@dongle-the-gadget @xmine64 

I tested Firefox and Nemo but without luck :(
The behavior the same.

Probably timeout is not the same for everyone or even each start it can be vary.

**Comment by sergiirepin** [comment]
Is it possible to add the timeout value as config value ?

**Comment by dongle-the-gadget** [comment]
Yeah the timeout hugely varies from one app to another. Looking back to Firefox, it could take as much as 5 seconds.

**Comment by sergiirepin** [comment]
@xmine64 Do you have an ideas about it ?

**Comment by dongle-the-gadget** [comment]
> We really need some delay, not because X410 resets attribute but because X410 windows are not considered as a valid window by MFE at the exact moment that they are created. They need some time.
