### ISSUE TITLE
Size Discrepancy of Min/Max/Close buttons when Maximized

### ISSUE THREAD

**Issue by WildByDesign** [MicaForEveryone/MicaForEveryone#218]
**Describe the bug**

When Win32 apps are maximized, the size of the Min/Max/Close buttons are sized the same as when the same Win32 apps are not maximized and cause overlapping.

This bug is specific to the **Extend Frame Into Client Area** option only. The bug only happens when that is enabled.

The **Blur Behind** option, when enabled, achieves similar visuals as the **Extend Frame Into Client Area** option. However, the **Blur Behind** option respects the proper sizing of the Min/Max/Close buttons.

**To Reproduce**

1. Enable **Extend Frame Into Client Area** for any Win32 app
2. Launch app and maximize app to see oversized/overlapping Min/Max/Close buttons (same size as non-maximized)

**Expected behavior**

The Min/Max/Close buttons should be larger when an app is not maximized, and smaller when maximized.

**Screenshots**

The yellow block shown in the screenshots is just the Close tooltip shown when hovering. Disregard the yellow.

![_mica1](https://user-images.githubusercontent.com/26308319/211071547-23cb4ad9-e6e3-4ddb-89d1-bc2fdab71f69.png) Maximized Win32 app with **Extend Frame Into Client Area** enabled. Overlapping area below. **42 pixel** height of Close button. This should match the **32 pixel** height. The problem with the **Extend Frame Into Client Area** option is that it seems to draw the Min/Max/Close buttons as if the maximized app was not maximized. Hopefully this little detail is helpful in finding the source of the bug.

![_mica2](https://user-images.githubusercontent.com/26308319/211071549-ead894d0-1db8-4e94-ab7e-d04da713b7e2.png) Maximized Win32 app with **Blur Behind** enabled. Normal as expected. **32 pixel** height of Close button.

![_mica3](https://user-images.githubusercontent.com/26308319/211071550-3c434251-76cf-4c35-9989-19b203f09826.png) Regular Win32 app window that is not maximized. **42 pixel** height of Close button.

**Windows Version**

Windows 11 Pro 22621.963

**Comment by dongle-the-gadget** [comment]
Seems to be a Windows bug.
