### ISSUE TITLE
Error code on start windows11

### ISSUE THREAD

**Issue by IWSM** [MicaForEveryone/MicaForEveryone#224]
Either I have this error, or it does not launch at all
<img width="299" alt="Capture d’écran 2023-01-16 135752" src="https://user-images.githubusercontent.com/63722574/212683752-ddabbd5c-941d-4313-aec1-2264571da12c.png">

**Comment by xmine64** [comment]
Could you please give more details? Do you have Visual C++ Runtime installed? Did you extract all files from the zip file?
