### ISSUE TITLE
'Remove Rule' button not showing when sidebar is not collapsed and language set other than English

### ISSUE THREAD

**Issue by toineenzo** [MicaForEveryone/MicaForEveryone#225]
**Describe the bug**
The Remove Rule button only shows in the sidebar when the window is resized narrow so the sidebar collapses, with every language set except English (the default). It will not show when the window is wider and the sidebar is not collapsed. Also the text for Add Rule flashes when resizing.

**To Reproduce**
1. Set other language than English
2. Resize window window wider so that the sidebar isn't collapsed
3. Remove Rule button is not being shown
4. Resize window window narrower so that the sidebar is collapsed
5. Remove Rule button is being shown in sidebar

**Expected behavior**
The Remove Rule button being shown regardless of set language, size of window or if the sidebar is collapsed

**Screenshots**
n/a, See video: https://youtu.be/VNO2wyX9_44

**Windows Version**
Windows 11 22H2 build 22621.1105 (Main Release)

**Comment by toineenzo** [comment]
Forgot to mention (I point it out in the video), but I can resize the window but maximize button is disabled??

**Comment by xmine64** [comment]
Thanks for reporting.
Maximize button is disabled on purpose.
I'll check what's wrong with the remove button. I guess it's because there's not enough space for it to show up.

**Comment by dongle-the-gadget** [comment]
It only happens in some languages (i.e. English and Chinese works fine, but not Nederlands)

**Comment by dongle-the-gadget** [comment]
Weird. The button is completely missing.
<img width="235" alt="image" src="https://user-images.githubusercontent.com/29563098/212734504-9a427d9d-428f-4cb6-b6b5-430ce12c7fbb.png">

**Comment by dongle-the-gadget** [comment]
@xmine64 your hypothesis is right. When the button labels get long enough, the remove button will move into the secondary commands section. However, we have hidden the entry way to secondary commands (via disabling the overflow button), then it shows up to the user as being completely missing.

**Comment by xmine64** [comment]
> When the button labels get long enough, the remove button will move into the secondary commands section.

We need to hide labels. We will need some room to add increase/decrease priority buttons anyway.

> I'm not quite sure about the flashing text though.

It happens during resize👀

**Comment by dongle-the-gadget** [comment]
How about moving the CommandBar outside the SplitPane when the pane is visible without an overflow button?

**Comment by GitExploraa** [comment]
Using English here and it still doesnt show, i think it affects all languages

**Comment by dongle-the-gadget** [comment]
This is a bug that can potentially affect all languages, though some are hit harder than others.

**Comment by GitExploraa** [comment]
> This is a bug that can potentially affect all languages, though some are hit harder than others.

i see, just wanted to confirm this though, hope it gets fixed soon

**Comment by toineenzo** [comment]
Maybe this also has to do with dpi scaling perhaps? (Looking at the flashing, just a guess). 

And also a solution could be to make the sidebar a little more wider. (would also but better cuz some process rules could be long strings)

**Comment by dongle-the-gadget** [comment]
I don't think that DPI scaling affects this, since the sidebar width is static and uses logical pixels (which is not affected by DPI) instead of physical pixels.
