### ISSUE TITLE
How to disable the custom titlebar on different profiles on chrome?

### ISSUE THREAD

**Issue by bigplayer-ai** [MicaForEveryone/MicaForEveryone#229]
I am trying to disable Windows 10 custom title bar on Google Chrome.
I am failing to do this because my Google Chrome is with profiles.
How can I disable the custom title bar on different profiles on chrome?
I have different profiles on my Google Chrome. I can't turn off the custom title bar by adding the argument (--disable-windows10-custom-titlebar) to Google Chrome.
Likewise, I want to disable Windows 10 custom title bar on all profiles.
Specific steps I did:
1) Have two or more profiles on Google Chrome
2) add the argument --disable-windows10-custom-titlebar to any shortcut
3) try to run the shortcut or apply the settings to the shortcut.
4) a new profile is opened with Windows 10 custom title bar turned on when opening the profile shortcut or an error when adding an argument to the global chrome shortcut, as shown in the images below.

To disable Windows 10 custom title bar on chrome by having an option or something, or force chrome to disable Windows 10 custom title bar with another workaround.

**The alternatives I've considered:**
I tried the argument on different shortcuts. In addition, I tried another argument (--disable-features=Windows10CustomTitlebar) on the shortcuts. But none worked.

Adding the argument --disable-windows10-custom-titlebar to specific profile chrome shortcut
[![adding the argument --disable-windows10-custom-titlebar to specific profile chrome shortcut][1]][1]

adding the argument --disable-windows10-custom-titlebar to global chrome shortcut
[![adding the argument --disable-windows10-custom-titlebar to global chrome shortcut][2]][2]

  [1]: https://i.stack.imgur.com/4wUbQ.png
  [2]: https://i.stack.imgur.com/TFn8y.png

**Comment by dongle-the-gadget** [comment]
[Read the manual please!](https://github.com/MicaForEveryone/MicaForEveryone/wiki/FAQ#chromium)

**Comment by bigplayer-ai** [comment]
> [Read the manual please!](https://github.com/MicaForEveryone/MicaForEveryone/wiki/FAQ#chromium)

How to disable the custom titlebar on different profiles on chrome?
I have different profiles on my google chrome, When having the shortcut to different profiles, I can't disable custom titlebar by adding the argument (--disable-windows10-custom-titlebar) to the shortcut as it will mess the whole profile thing on google chrome...
I want it to work on all profiles.
1) Have two or more profiles on google chrome
2) add the argument --disable-windows10-custom-titlebar to any shortcut
3) try to run the shortcut
4) a new profile is opened with windows 10 custom title bar turned on, How can I fix this?

**Comment by bigplayer-ai** [comment]
> [Read the manual please!](https://github.com/MicaForEveryone/MicaForEveryone/wiki/FAQ#chromium)

Please read my edited question.

**Comment by bigplayer-ai** [comment]
I fixed the issue by having the argument  --disable-windows10-custom-titlebar before the profile argument.
