### ISSUE TITLE
Mica for everyone wont open

### ISSUE THREAD

**Issue by foursplaysroblox** [MicaForEveryone/MicaForEveryone#230]
**Describe the bug**

After installing Windows 11 build 25281 Home Preview Dev channel

**To Reproduce**
1. Find a way to fix this problem

**Expected behavior**

Expected to open as usual

**Screenshots**

![image](https://user-images.githubusercontent.com/82078139/213617768-a7ae1f18-c53c-46a4-b658-dc52d30bd935.png)

**Windows Version**
E.g. Windows 10 build 19042, Windows 11 Build 22000, Windows 11 Build 25217 Insider Dev Channel, ...

Windows 11 Build 25281 Insider Dev Channel Home
**Additional context**

**Comment by dongle-the-gadget** [comment]
It looks like MFE failed to load XAML Islands, which is interesting.

**Comment by foursplaysroblox** [comment]
fixed already through installing msix version of Mica for everyone

**Comment by xmine64** [comment]
I believe it's because you don't have Visual C++ Runtime installed.
