### ISSUE TITLE
Wrong Mica Effect on chrome browser (check photos)

### ISSUE THREAD

**Issue by bigplayer-ai** [MicaForEveryone/MicaForEveryone#231]
**Describe the bug**
Wrong effect on chrome browser (check photos)
**To Reproduce**
1. Enable mica effect on google chrome. Disable native windows 10 title bar on chrome.
2. open chrome
3. See error

**Expected behavior**
Right mica effect.

**Screenshots**
![Default ](https://user-images.githubusercontent.com/119108387/213750994-e70ad67c-d877-4f43-9bb3-4db2812cb78e.png)
![System/dark mode](https://user-images.githubusercontent.com/119108387/213756458-a74fa56e-0a45-4187-8f0d-7e4d3b74d5e0.png)

**Windows Version**
E.g. Windows 10 build 19042, Windows 11 Build 22000, Windows 11 Build 25217 Insider Dev Channel, ...
Windows 11 22H2 Build 22621.1105

**Comment by dongle-the-gadget** [comment]
It might just be that Chrome is painting the tab backgrounds white.

**Comment by bigplayer-ai** [comment]
> It might just be that Chrome is painting the tab backgrounds white.

And how do I fix that?

**Comment by dongle-the-gadget** [comment]
Themes?

**Comment by dongle-the-gadget** [comment]
I mean using them.

**Comment by bigplayer-ai** [comment]
> I mean using them.

than I won't have any mica or acrylic effect on chrome lol

**Comment by bigplayer-ai** [comment]
Ok After lots of digging I fixed the issue by enabling extended into client area and disabling blur + tabbed backdrop type
