### ISSUE TITLE
Add support for Mica Alt?

### ISSUE THREAD

**Issue by bigplayer-ai** [MicaForEveryone/MicaForEveryone#232]
**Is your feature request related to a problem? Please describe.**
Hey can you add support for Mica Alt effect on windows 11?
**Describe the solution you'd like**
Mica Alt Effet (more transperent mica).
**Describe alternatives you've considered**
did not find any.
**Additional context**
https://www.bigtechwire.com/2022/09/06/microsoft-introduces-mica-alt-a-new-variant-of-mica-material-for-windows-app-developers/

**Comment by xmine64** [comment]
Already supported, requires Windows 11 build 22523 or higher.

**Comment by bigplayer-ai** [comment]
> Already supported, requires Windows 11 build 22523 or higher.

i have build 22621 and I still don't experience mica alt. How can I enable this?

**Comment by xmine64** [comment]
> i have build 22621 and I still don't experience mica alt. How can I enable this?

![image](https://user-images.githubusercontent.com/21140798/213785892-c1c2e662-600b-4a2e-b83c-6c0d8a52ed4f.png)

**Comment by yujinlin0224** [comment]
Why not just call Mica Alt but Tabbed? Just confused

**Comment by xmine64** [comment]
Because we added it before official release of 22H2 and that time it was called Tabbed.

**Comment by yujinlin0224** [comment]
Or add a note to Tabbed option, like change the label/description of Tbbed to "Tbbed (Mica Alt)"

**Comment by lts20050703** [comment]
Took me a while to find out that it's called Tabbed
Renaming it to something like Tabbed (MicaAlt) would be better in my opnion
