### ISSUE TITLE
Start minimized

### ISSUE THREAD

**Issue by FluffyDiscord** [MicaForEveryone/MicaForEveryone#235]
**Is your feature request related to a problem? Please describe.**
Enabling autostart (since I need to run mica on every boot, else its not working) make the mica window show up on every boot. Option to "start minimized" would be really neat since its annoying to close it up every single time

**Describe the solution you'd like**
Add toggle "auto start minimized"

**Describe alternatives you've considered**
None

**Comment by dongle-the-gadget** [comment]
I believe it shouldn't pop up a window unless something is malfunctioning?

**Comment by FluffyDiscord** [comment]
Somehow, after few reboots mica now starts minimized.

**Comment by xmine64** [comment]
You may have 2 startup tasks, when you open MFE for second time when it's already running it opens settings window.
Only check one of "run as administrator on startup" and "run on startup"
