### ISSUE TITLE
Similar to #193 but when I click on browse the app crash.

### ISSUE THREAD

**Issue by vathanac** [MicaForEveryone/MicaForEveryone#238]
Mica is already running as administrator.
In order to change path, I have to type in the path manually instead Browse option.
![MicaForEveryone_ySRkQ00nwJ](https://user-images.githubusercontent.com/87689818/214819940-a3640ce9-61e1-429e-95f8-a973ca5dfe01.gif)

**Comment by toineenzo** [comment]
I did have this ones but after reopening the app, it worked. Did you try to run it as admin?

**Comment by xmine64** [comment]
I just realized app crashes when you click on "Browse" when the app is running as admin.
Btw how it's related to #193 ?

**Comment by vathanac** [comment]
> I just realized app crashes when you click on "Browse" when the app is running as admin.
> 
> Btw how it's related to #193 ?

Rhe setting wasn't saving until I change config file location.

**Comment by xmine64** [comment]
I close this as #193 is fixed and we already have #198.
