### ISSUE TITLE
There is a problem with the system application window.

### ISSUE THREAD

**Issue by HelloOSMe** [MicaForEveryone/MicaForEveryone#239]
**Describe the bug**
As shown in the figure, when I configure the program in this way, the text on the window of File Explorer is not clear.

**Rule**
Process

**Target Application**
- Explorer.exe

**To Reproduce**
1. Open Mica for everyone
2. Open windows explorer
3. Open "blur behined"
5. Then click the window
6. You can't see the text.

**Expected behavior**
Clear fonts

**Screenshots**
![](https://helloosdisk.wikidot.com/local--files/file:github/micaforeveryone.png)  
![](https://helloosdisk.wikidot.com/local--files/file:github/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202023-01-27%20145901.png)  
![](https://helloosdisk.wikidot.com/local--files/file:github/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202023-01-27%20151656.png)
**Windows Version**
Windows 11 Build 22621

**Comment by toineenzo** [comment]
Windows explorer never really worked reliable with backdrop effect. Hopefully it will be more "theme friendly" when it gets separated from the shell and will be built with Xaml elements.

**Comment by xmine64** [comment]
Options under "Advanced" won't work properly with many application. We already mentioned that in the app and it's literally in the screenshot you sent. Also we have a lot of issues opened just for this.
