### ISSUE TITLE
TeamViewer is washed, Tried to add rule still experience the same issue of white wash color.

### ISSUE THREAD

**Issue by bigplayer-ai** [MicaForEveryone/MicaForEveryone#241]
**Describe the bug**
When starting micaforeveryone even though there is a rule for teamviewer processes. I still experience wash colors on team viewer as shown in [the image below:](https://user-images.githubusercontent.com/119108387/215331876-a5edce04-605b-4918-849a-16ce0cb1ab1a.png)
![image](https://user-images.githubusercontent.com/119108387/215331876-a5edce04-605b-4918-849a-16ce0cb1ab1a.png)

**Rule**
The rule used for the target application
I could not find the config file.
**Target Application**
- Application Name Teamviewer
- Application Version 15

**To Reproduce**
1. Go to MicaForEveryone
2. aDD Default rules for teamviewer
3. open teamviewer
4. See washed colors on teamviewer
![washed colors on teamviewer](https://user-images.githubusercontent.com/119108387/215331876-a5edce04-605b-4918-849a-16ce0cb1ab1a.png)
**Expected behavior**
Mica For everyone not applying its settings on teamviewer because of the rules...
**Screenshots**
![washed colors on teamviewer](https://user-images.githubusercontent.com/119108387/215331876-a5edce04-605b-4918-849a-16ce0cb1ab1a.png)
**Windows Version**
E.g. Windows 10 build 19042, Windows 11 Build 22000, Windows 11 Build 25217 Insider Dev Channel, ...
Windows 11 22H2 22621
**Additional context**

**Comment by toineenzo** [comment]
You forgot to set backdrop type to disabled to fix this. Not all apps react the same and are supported

**Comment by xmine64** [comment]
> You forgot to set backdrop type to disabled to fix this. Not all apps react the same and are supported

default doesn't touch anything but disabled tries to disable the backdrop if it's already enabled.

**Comment by bigplayer-ai** [comment]
Ok I fixed the errors, It was using windows process thatI needed to as a rule for it in addition to teamviewer processesOn 1 Feb 2023, at 8:05, Mohammad Amin ***@***.***> wrote:﻿

You forgot to set backdrop type to disabled to fix this. Not all apps react the same and are supported

default doesn't touch anything but disabled tries to disable the backdrop if it's already enabled.
