### ISSUE TITLE
MFE disables transparency on EverythingToolbar

### ISSUE THREAD

**Issue by dr-baba** [MicaForEveryone/MicaForEveryone#244]
I am using [EverythingToolbar](https://github.com/stnkl/EverythingToolbar) with MFE. With MFE enabled, the EverythingToolbar searchbox loses translucency and becomes solid. [Discussion topic on EverythingToolbar github](https://github.com/stnkl/EverythingToolbar/discussions/308)

Here is the intended behaviour:
![213898038-c8f76cc4-572e-481c-82bf-e420900e1aff](https://user-images.githubusercontent.com/50979846/216017140-ee8c0bf2-9856-438b-9bef-5191656df641.gif)

Here is behaviour with MFE enabled:

https://user-images.githubusercontent.com/50979846/216017249-42ed0210-1720-4326-8396-185d27829917.mp4

Is there any way to add the program as an exception into MFE? I am using the deskband version (Windows 10 taskbar toolbar) of EverythingToolbar.

**Comment by dongle-the-gadget** [comment]
EverythingToolbar uses the same APIs Mica For Everyone uses to achieve transparency control. In your case, it looks like the Mica effect got applied instead of the app's Acrylic.

To add an exclusion rule to MFE, you need to know either the process name or the window class name. Maybe open up Task Manager, try to find the EverythingToolbar process in the Processes tab, right click the process and click on "Go to details". That should give you the process name you need to enter in MFE's settings.

**Comment by dr-baba** [comment]
Unfortunately there is no process for the desk band version. I tried using Spy++ on the window: 
![image](https://user-images.githubusercontent.com/50979846/216029806-7d82411f-68ab-4f0b-a0fb-b266154dd8e6.png)

However adding this as a class rule doesn't seem to have any effect (both on Default and None). **I am not sure if I am putting it into MFE correctly.**
![image](https://user-images.githubusercontent.com/50979846/216029967-7a7cc3cb-ccf3-440a-88fc-53dbea4a2991.png)

It still only shows transparency once after restarting explorer and when opening EverythingToolbar again, it returns to a solid backgorund.

**Comment by dongle-the-gadget** [comment]
That is not possible. Click OK and go to the Processes tab, and click on the Process ID.

**Comment by dr-baba** [comment]
The previous comment's Spy++ screen was actually for the taskbar version not the deskband version. Since EverythingToolbar has 2 different versions. I was able to successfully fix the taskbar version since it does have have a process attached in Task manager (EverythingToolbar.Launcher.exe). This process was confirmed with Spy++ as well.

With the deskband version, the class ID seems to change with each restart of explorer. 
![image](https://user-images.githubusercontent.com/50979846/216038112-6cf4a6ab-e484-489f-ae98-0687b9a8d9e7.png)

Clicking on process ID leads to explorer again. However changing explorer's option in MFE does not seem to affect anything so I am not sure.
![image](https://user-images.githubusercontent.com/50979846/216038278-51520c98-4512-4453-8236-e140812ccfe3.png)

**Comment by dongle-the-gadget** [comment]
Have you made sure that everything is default + off and that you restarted?
