### ISSUE TITLE
Weird backdrop in Photoshop caused by MicaForEveryone

### ISSUE THREAD

**Issue by BlankShade98** [MicaForEveryone/MicaForEveryone#248]
Somehow, this app draws a weird backdrop/frame around the Photoshop window, and I have no idea how to get rid of it without disabling the whole MicaForEveryone app. The worst part of this issue is that ugly overlap with the taskbar. If there is a way to force exclude a specific process, that would be useful. If not, I think, it would be a great and very useful addition to MicaForEveryone.
The same issue can also be seen in other Adobe apps.
Screenshots describing the issue:
Backdrop behind the loading window:
![image](https://user-images.githubusercontent.com/49781392/216971787-a47c1149-4c78-4d01-8565-59c131f0e814.png)
Backdrop/frame overlapping with the taskbar:
![image](https://user-images.githubusercontent.com/49781392/216971882-bc414a47-b44d-408c-95b5-45a42b217ed5.png)

**Comment by xmine64** [comment]
https://github.com/MicaForEveryone/MicaForEveryone/wiki/FAQ#window-is-not-displaying-properly
