### ISSUE TITLE
washed "choose a folder/file" colors rule

### ISSUE THREAD

**Issue by bigplayer-ai** [MicaForEveryone/MicaForEveryone#253]
[ ] This is not about other apps being displayed weird or etc.
[ ] This is not about rendering issues that caused by a bug in the Windows.
[ ] I've read [FAQ](https://github.com/MicaForEveryone/MicaForEveryone/wiki/FAQ).
[ ] I've checked other issues and this is not a duplicate.

**Describe the bug**
mica for everyone washed colors on choose a file/folder. How can I add a rule to exclude this?
**To Reproduce**
1. Go to chosoe a folder in any application
2. See the error
![Clip_20230217_135923](https://user-images.githubusercontent.com/119108387/219648547-639bb727-8681-4937-9a46-bf72a24d8499.png)

**Expected behavior**
Unwashed colors
**Screenshots**
![Clip_20230217_135923](https://user-images.githubusercontent.com/119108387/219648564-468e1999-651c-444b-b9a8-3564db0384d5.png)
**Windows Version**
Windows 11 22h2 build 22621.1265
**Additional context**

**Comment by dongle-the-gadget** [comment]
Do you have Blur Behind/Extend Frame Into Client Area enabled?

**Comment by bigplayer-ai** [comment]
> Do you have Blur Behind/Extend Frame Into Client Area enabled?

On which rule(proccess/class)?
What is this choose a file/folder called? Is it the same as explrorer.exe?
How can I enable only on this window class? I want to know its type.

**Comment by dongle-the-gadget** [comment]
Try disabling it on #32770 (Dialog).

**Comment by xmine64** [comment]
I created issue templates with some notes on top of it, still people creating bug report for something that should be reported as third party issue. In fact should not get reported at all because it's in the issues, FAQ, issue template, and in the app itself.
