### ISSUE TITLE
Will not let me download .NET Core

### ISSUE THREAD

**Issue by ghost** [MicaForEveryone/MicaForEveryone#255]
**Describe the bug**
Will never let me download .NET Core. Already installed it and won't do ANYTHING.

**To Reproduce**
1. Open micaforeveryone
**Expected behavior**
Supposed to download .NET Core.

**Screenshots**

**Windows Version**
Windows 11 Build 22621

**Comment by dongle-the-gadget** [comment]
Make sure you have installed .NET Core 3.1 - the program will not do that itself.

**Comment by xmine64** [comment]
Please read the FAQ before opening new issues.

**Comment by spider623** [comment]
.net 3.1 was deprecated... thous no download link :)

**Comment by dongle-the-gadget** [comment]
There is, just hidden in the .NET website.
https://dotnet.microsoft.com/en-us/download/dotnet/3.1

**Comment by spider623** [comment]
Installing it like that will break winget since it will keep trying to upgrade it to 7 that is the latest stable, deprecated is deprecated

**Comment by spider623** [comment]
do note that the 6.0.14 is complaining because 3.1.32 is installed

**Comment by dongle-the-gadget** [comment]
Well as pointed out in one of the previous replies, switching to .NET 5+ isn’t a simple retargeting.

**Comment by dongle-the-gadget** [comment]
Tried installing the latest .NET Core 3.1 Desktop Runtime from the Microsoft website, I still can't see anything wrong.
<img width="865" alt="image" src="https://user-images.githubusercontent.com/29563098/223396325-bba757a0-8dbb-47a8-8802-a28342b4304f.png">

**Comment by dongle-the-gadget** [comment]
> do note that the 6.0.14 is complaining because 3.1.32 is installed

Older major versions of .NET Core (which includes .NET 5 and newer) shouldn't affect newer versions, probably something wrong is going on with your machine.
