### ISSUE TITLE
Corrupted config will make MFE unusable 

### ISSUE THREAD

**Issue by Marocco2** [MicaForEveryone/MicaForEveryone#256]
[x] This is not about other apps being displayed weird or etc.
[x] This is not about rendering issues that caused by a bug in the Windows.
[x] I've read [FAQ](https://github.com/MicaForEveryone/MicaForEveryone/wiki/FAQ).
[x] I've checked other issues and this is not a duplicate.

**Describe the bug**
After days of activity, upon a restart MFE is in a unrecoverable state and it's impossible to get it working without a reinstall.

**To Reproduce**
No steps known to reproduce the behavior

**Expected behavior**
It should always be working

**Screenshots**
![image](https://user-images.githubusercontent.com/3944248/219938380-5a2ce951-ac35-43ba-8acc-accae4e0e162.png)

**Windows Version**
Windows 11 22H2 x64

**Additional context**

**Comment by dongle-the-gadget** [comment]
How about reinstalling VCLibs?

**Comment by Marocco2** [comment]
> How about reinstalling VCLibs? https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/cpp/libraries/c-runtime-packages-desktop-bridge

Tried it right now, didn't help

**Comment by Marocco2** [comment]
If there is any logs I could send you, let me know how to retrieve them

**Comment by xmine64** [comment]
The second window is supposed to show you an error message but that window is not working either🙂
But I guess I already know what's wrong and I've fixed it in the dev branch. CI failed to build it but I'll fix it.

**Comment by dongle-the-gadget** [comment]
Maybe we should introduce a fallback window in case it doesn't work 😅

**Comment by xmine64** [comment]
> Maybe we should introduce a fallback window in case it doesn't work 😅

No I think it's [this](https://github.com/MicaForEveryone/MicaForEveryone/commit/96669f5c790f4c906f26178bcfc6563f8c491b83), MFE was crashing for me and I fixed it by adding this check before enabling file watcher.

**Comment by xmine64** [comment]
> Maybe we should introduce a fallback window in case it doesn't work 😅

Oh you mean the error window. Well we would never know if the window is displaying correctly or not=)) We would know if we get some error, but I guess we don't get any error message for this because then we would see another error message window.

**Comment by Marocco2** [comment]
As you notice, I did manage to have two "Discord" entries here

**Comment by xmine64** [comment]
This should be fixed on new version
