### ISSUE TITLE
MicaForEveryone cause black screen when tried to use Powertoys Text Extractor 

### ISSUE THREAD

**Issue by vathanac** [MicaForEveryone/MicaForEveryone#257]
[shafschwd comment on issues 20376](https://github.com/microsoft/PowerToys/issues/20376#issuecomment-1276309872)

**Comment by xmine64** [comment]
Please read the [FAQ](https://github.com/MicaForEveryone/MicaForEveryone/wiki/FAQ#window-is-not-displaying-properly)

You would need to create a rule for the text extractor app and set everything to default, then kill that app from task manager and restart it.
