### ISSUE TITLE
Explorer showing washed colors on first run only

### ISSUE THREAD

**Issue by bigplayer-ai** [MicaForEveryone/MicaForEveryone#260]
[ ] I've read [FAQ](https://github.com/MicaForEveryone/MicaForEveryone/wiki/FAQ).
[ ] I've restarted the affected app after adding rule for it.
[ ] I've checked other issues and this is not a duplicate.

**Describe the bug**
I have washed colors when starting any file explorer
**Rule**
The rule used for the target application

**Target Application**
- Application Name Explorer
- Application Version Explorer windows 11 22h2 build 22621.1265

**To Reproduce**
1. Go toexplorer
2. open first time
3. see washed colors
4. reopen the explroer
5. colors back to normal

**Expected behavior**
normal colors
**Screenshots**
![image](https://user-images.githubusercontent.com/119108387/220626722-322b8369-a726-49d9-801b-0a268d14dc7b.png)

**Windows Version**
E.g. Windows 10 build 19042, Windows 11 Build 22000, Windows 11 Build 25217 Insider Dev Channel, ...
windows 11 22h2 build 22621.1265

**Additional context**

**Comment by HighScorePlayer** [comment]
I encountered the same problem as you.
#260 marked.

**Comment by drannex42** [comment]
Try disabling it on #32770 (Dialog) class.

_Originally posted by @dongle-the-gadget in https://github.com/MicaForEveryone/MicaForEveryone/issues/253#issuecomment-1434546978_
