### ISSUE TITLE
MFE not launching after installation

### ISSUE THREAD

**Issue by manjit-b** [MicaForEveryone/MicaForEveryone#262]
<h2> The application does not launch at all!!</h2>
The application installs very smoothly and then when it encounters the missing >NET files, I can download them and install them too. But after that, when I try to open the application, it does not launch.

<h3>Methods I have tried</h3>

- Installed earlier, same version of windows and worked perfectly
- Installed on Program Files
- Installed on Program Files(x86)

<h3>--- I have tried older version too, but they do not seem to work at all! ---</h3>
A simple demonstration is shown below:
![Untitled](https://user-images.githubusercontent.com/100372553/221359811-298ea4f1-62b4-448e-9318-e81356a10717.gif)

**Comment by dongle-the-gadget** [comment]
Have you tried VCLibs? https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022

**Comment by CoolShades** [comment]
Not launching for me either. Tried the VC Libs as well.

**Comment by CoolShades** [comment]
I managed to fix it by installing MSIX file (after self signing) instead of the exe file.
