### ISSUE TITLE
quadruple clicking the tray icon makes 2 instances and then crashes

### ISSUE THREAD

**Issue by MuscularPuky** [MicaForEveryone/MicaForEveryone#265]
[ ] This is not about other apps being displayed weird or etc.
[ ] This is not about rendering issues that caused by a bug in the Windows.
[ ] I've read [FAQ](https://github.com/MicaForEveryone/MicaForEveryone/wiki/FAQ).
[ ] I've checked other issues and this is not a duplicate.

**Describe the bug**
![image](https://user-images.githubusercontent.com/93962018/221912733-64209310-26e0-4567-a0a4-49f020a23dc6.png)

**To Reproduce**
1. Go to tray icon
2. Click the MFE 4 times
3. close 1 instance
4. crashes

**Expected behavior**
it opens only 1 instance

**Screenshots**

**Windows Version**
Windows 11 NT 10.0.25300.1000

**Additional context**

**Comment by xmine64** [comment]
I can't reproduce this but thanks, I'll check what can I do about it.
