### ISSUE TITLE
Classic Win32 Notepad Menu Bar

### ISSUE THREAD

**Issue by WildByDesign** [MicaForEveryone/MicaForEveryone#267]
**Is your feature request related to a problem? Please describe.**

I have successfully applied Mica and Acrylic to the classic win32 version of Notepad because I don't like the UWP version of Notepad. Everything looks great, but unfortunately the menu bar does not get Mica or Acrylic applied to it.

**Describe the solution you'd like**

It would be great if the program could also apply Mica or Acrylic to the menu bar of programs.

**Describe alternatives you've considered**

Interestingly, the only win32 program that I have seen recently that can successfully apply Acrylic to the menu bar specifically is System Informer (previously Process Hacker). They have done something with their menu bar code which allows for Mica For Everything to apply Mica or Acrylic to the menu bar. From a programming perspective, I do not understand how they have achieved that with the menu bar.

**Screenshots**

![_notepadacrylic](https://user-images.githubusercontent.com/26308319/222477334-d90c8c57-af46-464b-9f10-d4d8167e6012.png)
![_notepadmica1](https://user-images.githubusercontent.com/26308319/222477336-693d4e52-3a23-4ea9-87d8-0a900d3c8a60.png)
![_notepadmica2](https://user-images.githubusercontent.com/26308319/222477339-d7377cf4-efd3-4bed-9faf-3fb3ac1ee86d.png)

As you can see in the System Informer screenshot below, they have done something to allow Mica or Acrylic to be applied to their menu bar:

![_systeminformeracrylic](https://user-images.githubusercontent.com/26308319/222477340-55e1f6a9-f360-4aaf-9bbf-db43d269c685.png)

**Comment by WildByDesign** [comment]
Issue not necessary now, closing.

**Comment by xmine64** [comment]
Look of each app really depends on the app itself, there's nothing that we can do about it, but you may want to try rectify11 project.
