### ISSUE TITLE
The brightness bar and volume bar color rendering error after the lower right control bar is expanded

### ISSUE THREAD

**Issue by liweiwa** [MicaForEveryone/MicaForEveryone#268]
[ ] I've read [FAQ](https://github.com/MicaForEveryone/MicaForEveryone/wiki/FAQ).
[ ] This bug keeps occurring

**Describe the bug**
Originally pink, it has been like this since updating the beta channel of 22624.1391

**To Reproduce**
Click to expand the control bar and it will appear

**Expected behavior**

**Screenshots**
<img width="273" alt="image" src="https://user-images.githubusercontent.com/115682965/223131742-8edc43fc-d9d7-4d3e-8954-f1dcd3c75174.png">

**Windows Version**
Windows 11 Build 226241391 Insider beta channel

**Comment by dongle-the-gadget** [comment]
MFE doesn't have the ability to modify XAML UI elements last I remember.

**Comment by xmine64** [comment]
Is it like this when MFE is not running?
