### ISSUE TITLE
Possible to disable Backdrop Type effects disappearing when window is not in focus?

### ISSUE THREAD

**Issue by camelfert** [MicaForEveryone/MicaForEveryone#274]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
I was wondering if it was possible to disable the functionality (optimization?) within Windows that removes the Backdrop Type/effects when a window that has support for them or has them applied is not in focus. I understand that it is probably intentional on Microsoft's end for visual hierarchy and performance among other reasons, but on higher end systems I feel like it would not impact much to disable it so that windows on other monitors maintain their effects. This could be implemented as a toggle of some kind within MFE (or as its own standalone thing if out of scope of the project?).

**Describe alternatives you've considered**
Is there a registry tweak of some kind or a hidden setting somewhere in Windows that could potentially do this? Another program that may already do this? (I have tried to research both things but to no avail.)

**Additional context**
Below I have an example using the app that caused me to write this request, Cider. It looks fantastic when it's in focus, but as soon as you click out of the window it goes back to being grey and lacking the effect. This is apparent across the entire OS however and with every window.

**Window in focus (using Tabbed Backdrop Type):** 
![backdroptypefocused](https://user-images.githubusercontent.com/29033079/225780865-c17e896f-fedd-41b3-94f1-c3d290decf9a.png)

**Window not in focus:**
![backdroptypeunfocused](https://user-images.githubusercontent.com/29033079/225780867-d28ec797-4f8b-43cc-ad04-403cd42fde51.png)

Thank you!

**Comment by dongle-the-gadget** [comment]
No, not currently. This feature requires DWM hooking.
