### ISSUE TITLE
"Show accent colors on titile bars and window borders" in Personalization option Windows 11 disables backdrop effect

### ISSUE THREAD

**Issue by UnclWish** [MicaForEveryone/MicaForEveryone#275]
1. Go to 'Personalization' in settings Windows 11.
2. Enable 'Show accent colors on titile bars and window borders'
3. Backdrop effect dissappears.

It's need to apply effect on title bars with accent color.

Windows 11 Build 22621.1413

**Comment by xmine64** [comment]
It's not a bug in a MFE, it's how Windows works.

**Comment by SteffanDonal** [comment]
This could be fixed by this PR: https://github.com/MicaForEveryone/MicaForEveryone/pull/259
Setting the caption colour to "None" will allow the backdrop to remain visible in the title bar.

**Comment by emvaized** [comment]
> This could be fixed by this PR

Unfortunately, this PR doesn't introduce "None" option for the backdrop, it only introduces option to set solid color for the titlebar.

**Comment by emvaized** [comment]
I ended up using [this ](https://gist.github.com/ericreeves/fd426cc0457a5a47058e1ad1a29d9bd6) Autohotkey script, which adds border to active window — I modified it to use system accent color. 
This way I could disable titlebar coloring in Windows settings to use Mica effects in titlebar, and preserve active window's border.
