### ISSUE TITLE
I can't install using MSIX file, it says "Contact your app dev"

### ISSUE THREAD

**Issue by Lime22H2** [MicaForEveryone/MicaForEveryone#281]
I tried all other ways to install after MSIX failed, and I can't even use the app.

**Comment by dongle-the-gadget** [comment]
Are you sure you have [installed the certificate](https://github.com/MicaForEveryone/MicaForEveryone/wiki/Installation#msix-file)?

**Comment by TheFurryDevil** [comment]
Hey, the certificate expired 3 days ago ^^

**Comment by xmine64** [comment]
Updated the certificate, you can install now.
