### ISSUE TITLE
Explorer window blur disabled after resizing or maximizing

### ISSUE THREAD

**Issue by SolidBlock-cn** [MicaForEveryone/MicaForEveryone#286]
[ - ] This is not about other apps being displayed weird or etc.
[ - ] This is not about rendering issues that caused by a bug in the Windows.
[ - ] I've read [FAQ](https://github.com/MicaForEveryone/MicaForEveryone/wiki/FAQ).
[ - ] I've checked other issues and this is not a duplicate.

**Describe the bug**
The explorer windows is not blurred after resizing. It is also not blurred if it is not the activated window.

**To Reproduce**
1. Enable extend to client for explorer.
2. Resize of maximize the explorer.

**Screenshots**
Before resizing:
![图片](https://user-images.githubusercontent.com/32444848/232948483-1e44c751-a990-4030-815b-0813ed6e1283.png)
After resizing:
![图片](https://user-images.githubusercontent.com/32444848/232948517-ee2ac0e5-40d9-4d5e-a2e4-5b4f244e00ff.png)

**Windows Version**
Windows 11 22H2

**Comment by dongle-the-gadget** [comment]
Try https://github.com/MicaForEveryone/ExplorerFrame/releases/tag/v0.2.0.0

**Comment by SolidBlock-cn** [comment]
> Try https://github.com/MicaForEveryone/ExplorerFrame/releases/tag/v0.2.0.0
Thanks! It works fine now.

**Comment by chibao2k3** [comment]
> Hãy thử [https://github.com/MicaFor Everyone /ExplorerFrame/releases/tag/v0.2.0.0](https://github.com/MicaForEveryone/ExplorerFrame/releases/tag/v0.2.0.0)

How to user it? I don't know and I can't open it

**Comment by dongle-the-gadget** [comment]
Basically you download the ZIP, extract it all somewhere and run ExplorerFrame.exe. It launches silently in the tray though, but you should see Explorer's frame being extended.
