### ISSUE TITLE
Duplicated instance crashes MFE

### ISSUE THREAD

**Issue by MuscularPuky** [MicaForEveryone/MicaForEveryone#290]
[v] This is not about other apps being displayed weird or etc.
[v] This is not about rendering issues that caused by a bug in the Windows.
[] I've read [FAQ](https://github.com/MicaForEveryone/MicaForEveryone/wiki/FAQ).
[ ] I've checked other issues and this is not a duplicate.

**Describe the bug**
multiple clicking on system tray causes crash

**To Reproduce**
1. mutiple click (3~4 times) the MFE icon on system tray
2. MFE launched
3. close 2 instances

**Expected behavior**
only 1 instance launches or 2 instances close

**Screenshots**
![image](https://github.com/MicaForEveryone/MicaForEveryone/assets/93962018/2f96540d-939b-452b-bbaa-17299ac8ce4d)

**Windows Version**
E.g. Windows 11 NT 10.0.25357.1 but no matter windows version

**Additional context**
#265

**Comment by xmine64** [comment]
Thanks for reporting this issue, it should not be possible to open multiple instances of Settings window. I'll check and fix it.

**Comment by dongle-the-gadget** [comment]
Should be closed by now, but for some reason didn't.
