### ISSUE TITLE
Mica doesn't work, and loads as white window at start up

### ISSUE THREAD

**Issue by Mal-content** [MicaForEveryone/MicaForEveryone#292]
[✓] This is not about other apps being displayed weird or etc.
[✓] This is not about rendering issues that caused by a bug in the Windows.
[✓] I've read [FAQ](https://github.com/MicaForEveryone/MicaForEveryone/wiki/FAQ).
[✓] I've checked other issues and this is not a duplicate.

**Describe the bug**
Mica worked for me for past last week, then suddenly without me changing anything every time i start pc it loads as white window and doesn't work. Images how it looks below. 

After app is started it displays: https://i.imgur.com/2iw80fJ.png when I double click taskbar icon it shows this https://i.imgur.com/i3ZJZmB.png App doesn't hang as i can click X i top right corner and it will be closed.

**To Reproduce**
1. For me just start PC.

**Expected behavior**
Load UI and work.

**Windows Version**
Windows 11 Build 22H2

**Comment by ViitoWee** [comment]
I believe I am having the same issue.
Mica has worked for me for about 2 months, and the bug occurred suddenly without me changing anything.
My windows are black but I'm pretty sure that has to do with Rectify11's light and dark theme.

When the app is started, do you only see that one white window, or are there two of them like in the image below?
https://imgur.com/hGBxow9
I can't help you, I'm just checking if we have the same issue.

**Windows Version**
Windows 11 Home 22H2 build 22621.525

**Comment by Mal-content** [comment]
Sometimes two windows pop up sometimes one - not sure what it depends on. But yea seem similar.

**Comment by Return761** [comment]
I'm having the same issue for a long time. And if u press any key it will close.
**Windows Version**
Windows11 23H2 25381.1

**Comment by 8KCoffeeWizard** [comment]
In #266 an user had mentioned that this issue occurs due to a corrupted config file, and that seems to be the case.

I managed to fix it by deleting the config file in `~\AppData\Local\Mica For Everyone` and replacing it with the default config file [found here](https://github.com/MicaForEveryone/MicaForEveryone/blob/master/MicaForEveryone/Resources/MicaForEveryone.conf).

I have not found the exact cause for it yet though.

**Comment by Mal-content** [comment]
Thank you that fixed issue.
