### ISSUE TITLE
Resizing a window horizontally still breaks the Mica Effect.

### ISSUE THREAD

**Issue by codyisland** [MicaForEveryone/MicaForEveryone#303]
A year ago, a user [posted ](https://github.com/MicaForEveryone/MicaForEveryone/issues/151) about this issue, and it was closed. Well, on version 13.0.0 and every version I install, regardless if it is .exe or .msix, it still occurs. When you try to resize any window that is using MFE, when you drag on the right and left sides of it, the Mica/Acyrlic/Tabbed effect goes away and the window fills up with your accent color.

**Expected behavior**
The effect from MFE is not supposed to disappear when dragging the right and left edge of the window.

Here is a video of it.

https://github.com/MicaForEveryone/MicaForEveryone/assets/75167869/87098bd4-7a63-4397-979a-de4a54bf17dd

**Windows Version**
Edition	Windows 11 Home
Version	22H2
Installed on	‎11/‎17/‎2022
OS build	22621.1928
Experience	Windows Feature Experience Pack 1000.22644.1000.0

**Comment by dongle-the-gadget** [comment]
Try https://github.com/MicaForEveryone/ExplorerFrame/releases/tag/v0.2.0.0?

**Comment by codyisland** [comment]
That fix the issue from dragging right to left, but when I open file explorer, it opens without the mica effect, and only when I click off does it and return does it apply it. Same thing with the run window. Notepad opens correctly.

https://github.com/MicaForEveryone/MicaForEveryone/assets/75167869/fbf270f4-415a-42b1-9c29-8b12eae4bef3

**Comment by dongle-the-gadget** [comment]
Strange. ExplorerFrame is supposed to apply the effect when a new FE window opens.

**Comment by xmine64** [comment]
This is either a bug in Windows or the app you're using, There's nothing to do with Mica for Everyone to fix this.
