### ISSUE TITLE
Latest version is crashing when trying to add a new process rule

### ISSUE THREAD

**Issue by Void48** [MicaForEveryone/MicaForEveryone#307]

**Comment by LoveJessyChen** [comment]
1.3.1.1 can't work with Acrylic, but 1.3.0.1 can work normally

**Comment by xmine64** [comment]
Sorry, I'll fix it as soon as possible

**Comment by warkorrea78** [comment]
el aplicativo no esta trabajando en su totalidad

**Comment by blxckhundred** [comment]
Same here on latest version
