### ISSUE TITLE
The language setting in the application does not have Traditional Chinese.

### ISSUE THREAD

**Issue by jay900604** [MicaForEveryone/MicaForEveryone#310]
I don't see the Traditional Chinese language in the application settings.

**Comment by xmine64** [comment]
I can see there are 2 Chinese languages, are you sure?
<img width="143" alt="image" src="https://github.com/MicaForEveryone/MicaForEveryone/assets/21140798/cad09745-6248-4bc4-b8b8-9c658f4ca7be">

**Comment by jay900604** [comment]
One of them is 中文简体 ( zh-Hans ), the other 日本語 ( ja ) is the language used in Japan, and 中文繁體 ( zh-Hant ) is not seen.
