### ISSUE TITLE
Acrylic can‘t work in latest version

### ISSUE THREAD

**Issue by LoveJessyChen** [MicaForEveryone/MicaForEveryone#312]
1.3.1.1 can't work with Acrylic, but 1.3.0.1 can work normally

**Comment by chuck00000** [comment]
Same issue, don't have transparency effects.

**Comment by AndiDink00x** [comment]
can you drop an example pic of this issue ?

**Comment by dongle-the-gadget** [comment]
This should be fixed in 1.3.1.2
