### ISSUE TITLE
1.3.1.1 does not correctly apply to apps

### ISSUE THREAD

**Issue by B01scout** [MicaForEveryone/MicaForEveryone#315]
**Describe the bug**
Version 1.3.0.0 worked fine and immediately applied the mica/acrylic/tabbed design to title bars of apps.
Version 1.3.1.1 does not apply anything to starting apps. Only after altering settings does the effect apply to currentl title bars.

**To Reproduce**
1. Start 1.3.1.1.
2. Save settings.
3. Start any app and see the setting not being applied.
4. Keep current active windows and alter Mica settings.
5. Now the settings actually apply (any new window will be ignored again).

**Expected behavior**
Correctly apply Mica settings on starting apps.

**Screenshots**
Window with 1.3.1.1 (incorrect)
![1311](https://github.com/MicaForEveryone/MicaForEveryone/assets/74605801/73c8d89d-97ef-478a-914b-6d9bb2ae3547)

Window with 1.3.0.0 (correct)
![1300](https://github.com/MicaForEveryone/MicaForEveryone/assets/74605801/3ffe936e-dcbf-492a-ac3e-fea3defbc9bb)

**Windows Version**
Windows 11 22H2 (Build 22621. 1928)

**Additional context**
Worked perfectly with 1.3.0.0.

**Comment by rodolfol95** [comment]
1.3.1.1 it not working for me at all at least with build 23493 from Dev chanel revert back to 1.3.0.0 works fine again :) 

I think latest version is broken

**Comment by Legend0804** [comment]
I'm also facing same issue.
But thing is, I uninstalled 1.3.1.1 and installed 1.3.0.0 and issue is still there

**Comment by amzon-ex** [comment]
Same issue! Worked perfectly with v1.3.0.0

**Comment by rodolfol95** [comment]
Yes 100% sure 1.3.1.1 it's broken at least on latest Dev Preview Build 23934 I never had any problem with MFE on any insider build ever

**Comment by Denicline** [comment]
same issue. win ver 22H2 22621.1928

**Comment by dongle-the-gadget** [comment]
I've been trying to investigate this - and seems like it is due to the event hook not triggering. The P/Invoke enum declaration is wrong, but it was still not working when I changed it for some reason.

**Comment by Driver92** [comment]
Same here, it's completely broken and only triggers when changing settings for that class. After system restart it seems to work for a while, but not for long.

**Comment by dongle-the-gadget** [comment]
I'm guessing that this is a threading issue, since you need an active message pool (`GetMessage` and stuff) in order for `SetWinEventHook` to work.

**Comment by dongle-the-gadget** [comment]
Can anyone test the [latest build in Actions](https://github.com/MicaForEveryone/MicaForEveryone/actions/runs/5553134857) and see if the bug is fixed?

**Comment by B01scout** [comment]
> Can anyone test the [latest build in Actions](https://github.com/MicaForEveryone/MicaForEveryone/actions/runs/5553134857) and see if the bug is fixed?

Yes, that fixed it for me.

**Comment by rodolfol95** [comment]
> Can anyone test the [latest build in Actions](https://github.com/MicaForEveryone/MicaForEveryone/actions/runs/5553134857) and see if the bug is fixed?

YES, took a while but you got it finally a fully working version and I don't even need to use explorer frame!!

**Comment by amzon-ex** [comment]
Awesome! Are you planning to release this as a hotfix or something soon?

**Comment by dongle-the-gadget** [comment]
1.3.1.2 has been released on GitHub for this issue. It will be published on Winget soon (I have to manually PR it due to the action failing).
