### ISSUE TITLE
Windows 11 22H2 Adding rule crash

### ISSUE THREAD

**Issue by SPLESHER1** [MicaForEveryone/MicaForEveryone#323]
[ ] This is not about other apps being displayed weird or etc.
[ ] This is not about rendering issues that caused by a bug in the Windows.
[ ] I've read [FAQ](https://github.com/MicaForEveryone/MicaForEveryone/wiki/FAQ).
[ ] I've checked other issues and this is not a duplicate.

**Describe the bug**

**To Reproduce**
1. Go to 'Mica For Everyone'
2. Click on 'Plus Icon, then create rule or for class or process'

**Expected behavior**
Program will simply crash without any error

**Screenshots**

**Windows Version**
Windows 11 22H2 22621.1848

**Additional context**
I saw in FAQ that crash exists on older versions of Windows 11, but I have 22H2 which is way newer and says it's supported

**Comment by simear2004** [comment]
同样的问题

**Comment by tilsgee** [comment]
same here. i'm in canary insider build 25393.1

**Comment by KeeLee2005** [comment]
#307

**Comment by Darikzen** [comment]
saaaame

**Comment by Darikzen** [comment]
> Seems to be fixed for me in the latest commits.

updated today, have tried just now and the problem still presents

**Comment by dongle-the-gadget** [comment]
Well did you clone the source code from GitHub/using Action builds or did you use Releases?

**Comment by Darikzen** [comment]
> Well did you clone the source code from GitHub/using Action builds or did you use Releases?

I just used Releases. Don't quite understand how to build from source code, but I'll try and check now, thanks

**Comment by Darikzen** [comment]
well, nope.
as I understand, it should load from Installer.iss through InnoSetup, but I just keep getting different errors  when I try to make an installer through it.
and while I managed to resolve a few, they keep spawning

**Comment by dongle-the-gadget** [comment]
You can try downloading through Actions: https://github.com/MicaForEveryone/MicaForEveryone/actions/runs/5533151624

**Comment by Darikzen** [comment]
thank you, it fixed everything

**Comment by simear2004** [comment]
> You can try downloading through Actions: https://github.com/MicaForEveryone/MicaForEveryone/actions/runs/5533151624

虽然添加规则不崩溃了，但是添加的规则设置的效果不能自动加载了，需要手动切换选择后才有效果

Although adding rules does not crash, the effect of the added rule settings cannot be automatically loaded and needs to be manually switched to have an effect

**Comment by dongle-the-gadget** [comment]
You mean that the rule does not apply to new windows?

**Comment by simear2004** [comment]
> You mean that the rule does not apply to new windows? Message ID: ***@***.***>

是的，比如，添加一个应用程序名的规则，将这个规则的模糊类型设置为 亚克力 ，并把模糊特效打开；此时打开规则的应用程序，窗口并不会加载设置的效果，需要去手动选择切换 模糊类型或模糊特效，应用程序效果才生效

Yes, for example, add a rule for the application name, set the fuzzy type of this rule to Acrylic, and turn on the fuzzy special effects; At this point, open the rule application, and the window will not load the set effect. You need to manually choose to switch the blur type or blur special effect for the application effect to take effect

**Comment by dongle-the-gadget** [comment]
@simear2004 A bug report has already been opened for it: #315.

**Comment by dongle-the-gadget** [comment]
Fixed in 1.3.1.2 on GitHub.

**Comment by blxckhundred** [comment]
Again crashing on the latest version
