### ISSUE TITLE
MFA is stuck on the .net core warning dialog.

### ISSUE THREAD

**Issue by nac5604** [MicaForEveryone/MicaForEveryone#327]
[x] This is not about other apps being displayed weird or etc.
[x] This is not about rendering issues that caused by a bug in the Windows.
[x] I've read [FAQ](https://github.com/MicaForEveryone/MicaForEveryone/wiki/FAQ).
[x] I've checked other issues and this is not a duplicate.

**Describe the bug**
I cannot open Mica For Everyone, because there is a dialog that says I do not have .NET Core installed. I click the Yes button on this dialog to install .NET Core, but it seems to do nothing.

**To Reproduce**
1. Open Mica For Everyone
2. Hit Yes on the dialog that pops up.

**Expected behavior**
I expected Mica For Everyone to install .NET Core for me, or at least give me a version number to install manually.

**Screenshots**
![image](https://github.com/MicaForEveryone/MicaForEveryone/assets/85867267/92eaeb9c-dce3-4b61-abd1-bf90995a1f91)

**Windows Version**
Windows 11 22H2

**Additional context**
I've installed .NET Core 7.0, and the problem is persisting.

**Comment by dongle-the-gadget** [comment]
It's a .NET bug, also MFE requires [.NET Core 3.1 Runtime](https://dotnet.microsoft.com/download/dotnet/3.1)
