### ISSUE TITLE
What .NET version are we supposed to install?

### ISSUE THREAD

**Issue by TinfoilOS** [MicaForEveryone/MicaForEveryone#329]
[ * ] This is not about other apps being displayed weird or etc.
[ * ] This is not about rendering issues that caused by a bug in the Windows.
[ * ] I've read [FAQ](https://github.com/MicaForEveryone/MicaForEveryone/wiki/FAQ).
[ * ] I've checked other issues and this is not a duplicate.

**Describe the bug**
Either version of .NET Core (7.0 and 6.0) from MS website does not remove the error when opening the application. Additionally, clicking the button in the dialog box does not open or start a download. Nowhere is it listed what .NET version is meant to be used.

**To Reproduce**
1. Run MicaForEveryone.EXE
2. See error popup (pictured)
3. Try clicking the Download button
4. It doesn't work
5. Install .NET Core 7.0 SDK from Microsoft website
6. Run MicaForEveryone and see error again
7. Do the same but with .NET Core 6.0 instead

**Expected behavior**
The application should work after installing .NET Core, and the download button in the error popup should at least point you in the right direction. It should also be listed what .NET versions work with this application.

**Screenshots**
![micaerror](https://github.com/MicaForEveryone/MicaForEveryone/assets/88356560/a2df3225-4623-46ef-bfc5-5a4781fd0955)

**Windows Version**
Windows 10 22H2 build 19045.3208

**Additional context**
I am a software developer and have multiple Visual Studio, Visual C++, and .NET (runtime and core) versions installed.

**Comment by TinfoilOS** [comment]
Installed an older version of .NET Core and it worked. Nevermind!

**Comment by xmine64** [comment]
https://github.com/MicaForEveryone/MicaForEveryone/wiki/Installation#system-requirements
