### ISSUE TITLE
Option to apply Mica effects only to foreground windows

### ISSUE THREAD

**Issue by emvaized** [MicaForEveryone/MicaForEveryone#332]
**Is your feature request related to a problem? Please describe.**
For me performance of foreground maximized window noticably worsenes if there's another maximized window behind it (both with Mica background enabled). Even scrolling becomes junky.

**Describe the solution you'd like**
I think that it makes sense to include an option to not apply Mica effects to windows which are not currently visible (fully behind other windows)

**Comment by dongle-the-gadget** [comment]
Detecting overlapped windows is a highly expensive operation, and not something we can easily do.

**Comment by emvaized** [comment]
> Detecting overlapped windows

Maybe then solution would be just to detect maximized foreground window, and disable Mica effects for all other windows?

**Comment by xmine64** [comment]
Windows greys out Mica on unfocused windows anyway,

**Comment by emvaized** [comment]
@xmine64 
Yes, it works this way with apps which support the Mica effect out of the box (for example, Calculator app, or Mica settings window). 

But it doesn't work this way with apps which get the effect created by Mica for everyone app. Here's quick example — MicaForEveryone settings window (focused) over VSCode window (with transparent window setting + Mica effect applied by MFE). You can clearly see that VSCode background does not get greyed out, and you can see background wallpaper through it: 
![изображение](https://github.com/MicaForEveryone/MicaForEveryone/assets/37851576/95bcb28b-7cf6-421d-a575-a9e0bbec6b58)

**Comment by xmine64** [comment]
> However, I just found that sometimes even windows Mica'ed by the app get grayed out properly — for example, Firefox window. It's really confusing why greying out works for some windows, and doesn't for others...

All windows supposed to get greyed out, if a window doesn't then it's a bug in the Windows itself.

**Comment by emvaized** [comment]
Yep, I see now it's an issue with specific apps which turned out to apply some transparency effect on their own. Closing this.
