### ISSUE TITLE
Red color after uninstalled

### ISSUE THREAD

**Issue by GemokLaw** [MicaForEveryone/MicaForEveryone#334]
Hi Team,

After the software was uninstalled, some part of my windows 11 turned red, please help.

Some loading bar, tick box and etc, please refer to screenshot attached as below.
![Screenshot 2023-07-26 155134](https://github.com/MicaForEveryone/MicaForEveryone/assets/140597954/6f276ef2-0576-4f6b-9f5f-f410eebccd42)
![Screenshot 2023-07-26 155210](https://github.com/MicaForEveryone/MicaForEveryone/assets/140597954/edc7b8cf-4ae6-4ecf-8158-a8dd227a6622)

**Comment by xmine64** [comment]
This has nothing to do with MFE, check what else did you do to your system. It's probably your accent color set to red.
