### ISSUE TITLE
Some title-bars from some system apps are unthemed

### ISSUE THREAD

**Issue by seventhstorm** [MicaForEveryone/MicaForEveryone#346]
I am experiencing this in some windows. I have used rectify11 as well as startallback. 
Any solution to fix this?
![image](https://github.com/MicaForEveryone/MicaForEveryone/assets/69987596/da18e4a1-633c-4d1a-b55f-97db20651975)

**Comment by dongle-the-gadget** [comment]
I'm not sure what you meant by "unrendered".

**Comment by dongle-the-gadget** [comment]
Can you show me the original?

**Comment by seventhstorm** [comment]
I had to patch Windows again using Secure Theme Patcher. Seems to have solved the issue. 
![image](https://github.com/MicaForEveryone/MicaForEveryone/assets/69987596/43fc6ba2-8917-46cf-a0ee-250021904320)

**Comment by seventhstorm** [comment]
![image](https://github.com/MicaForEveryone/MicaForEveryone/assets/69987596/0b78b78c-ccec-441b-b1e2-18d478aeebe7)
