### ISSUE TITLE
Disable micah on specific app rule.

### ISSUE THREAD

**Issue by CheezyFriez12** [MicaForEveryone/MicaForEveryone#347]
**Is your feature request related to a problem? Please describe.**
Some apps don't work very well with mica for everyone, and have graphical issues such as certain areas being pitch black, text using light mode colors in dark mode, text using dark mode colors in light mode, etc.

**Describe the solution you'd like**
Add an option to disable mica for everyone when creating an app rule

**Describe alternatives you've considered**
I've tried messing with the different app rule settings to disable mica for everyone effects, but It did not work.
**Additional context**
Some examples

Dolphin emulator
![image](https://github.com/MicaForEveryone/MicaForEveryone/assets/78517374/77b88ff3-4fbd-499c-bfe5-497052dafae9)

AOMEI Partition Assistant
![image](https://github.com/MicaForEveryone/MicaForEveryone/assets/78517374/88ba4f1a-6759-4f5a-a299-6a4422877010)

**Comment by dongle-the-gadget** [comment]
Set everything to Default (or toggled off).
