### ISSUE TITLE
'Extend Frame Into Client Area' works at first, but not when i maximize or create tabs in FIle Explorer

### ISSUE THREAD

**Issue by Dev-Chuon** [MicaForEveryone/MicaForEveryone#373]
[✅] This is not about other apps being displayed weird or etc.
[✅] This is not about rendering issues that caused by a bug in the Windows.
[✅] I've read [FAQ](https://github.com/MicaForEveryone/MicaForEveryone/wiki/FAQ).
[✅] I've checked other issues and this is not a duplicate.

**Describe the bug**
'Extend Frame Into Client Area' in Advanced is change to default view (black like it's turn off) when maximize or create other tabs in FIle Explorer (2️⃣&3️⃣).
1️⃣  Normal
![image](https://github.com/MicaForEveryone/MicaForEveryone/assets/146414131/fa1a2db7-d8c8-4f86-8a9e-fa1d31470699)
2️⃣ Bug 1:
![image](https://github.com/MicaForEveryone/MicaForEveryone/assets/146414131/7473df87-8be8-4070-b974-d3ff01a9e59c)
3️⃣ Bug 2:
![image](https://github.com/MicaForEveryone/MicaForEveryone/assets/146414131/2b7633cf-eed5-4906-af9e-3b9508ece93d)

**Windows Version**
i've try 3 differents insider builds channel on my laptop but the bugs is still there

**Additional context**
~I think that the new redesigned File Explorer using new based app on recently windows 11 update break MicaForEveryone~

**Comment by dongle-the-gadget** [comment]
Not a bug in MFE - have you tried https://github.com/MicaForEveryone/ExplorerFrame

**Comment by Dev-Chuon** [comment]
> Not a bug in MFE - have you tried https://github.com/MicaForEveryone/ExplorerFrame

thanks, it fixed my problem😁
