### ISSUE TITLE
Add option to run on startup as administrator

### ISSUE THREAD

**Issue by muznyo** [MicaForEveryone/MicaForEveryone#38]
Some apps, for example cmd isn´t affected by mica for everyone unless it´s launched as administrator.

The problem is that mica for everyone is started on startup as normal app, but not as an app opened by administrator.

It would be much easier to have this option.

**Comment by minusium** [comment]
I can create startup task with task scheduler to bypass UAC, but it needs a lot of works.

**Comment by dongle-the-gadget** [comment]
Unfortunately, using Task Scheduler creates leftover junk after uninstallation, which is kind of defeating the ideology of MSIX (clean uninstalls).
