### ISSUE TITLE
The program can't download .net runtimee itself

### ISSUE THREAD

**Issue by onichan0923** [MicaForEveryone/MicaForEveryone#389]
When I launch the program after install, a window pop up saying ''To run this application, you must install .NET core. Would you like to download it now ?''
I clicked yes, but nothing happened. So I downloaded .net 8.0, which is the latest, but still not working. After some search, I found that the prgram needs .net 3.1.
Could you please fix it, or at least specify the version of needed runtime? For example, ''To run this application, you must install .NET core **3.1**.''

**Comment by dongle-the-gadget** [comment]
> Could you please fix it, or at least specify the version of needed runtime? For example, ''To run this application, you must install .NET core 3.1.''

No, that error message is created by .NET, not us.
