### ISSUE TITLE
It says to install .NET core, even when I already have it installed

### ISSUE THREAD

**Issue by alexkisser** [MicaForEveryone/MicaForEveryone#398]
[Yes] This is not about other apps being displayed weird or etc.
[Yes] This is not about rendering issues that caused by a bug in the Windows.
[Yes] I've read [FAQ](https://github.com/MicaForEveryone/MicaForEveryone/wiki/FAQ).
[Yes] I've checked other issues and this is not a duplicate.

**problem**
Whenever I try running it, it says to install .NET core, even when I already have it installed

**How to reproduce**
1.idk use my pc?

**Expected behavior**
I expected it to run normally after installing but nah

**Screenshots**
![image](https://github.com/MicaForEveryone/MicaForEveryone/assets/153332763/51a496c5-4f0c-4380-bfd3-48379b076c57)
![image](https://github.com/MicaForEveryone/MicaForEveryone/assets/153332763/ef8fe266-02e9-47c2-a7d5-92d5a8599b3c)

**Windows Version**
![image](https://github.com/MicaForEveryone/MicaForEveryone/assets/153332763/ff39cb7b-dafb-46b6-8ef7-b941315771ef)

**Additional context**
nothing really

**Comment by cosigyn** [comment]
I can reproduce this.

**Comment by alexkisser** [comment]
how

**Comment by cosigyn** [comment]
Install the latest version of 'MicaForEveryone'
Open the application

**Comment by alexkisser** [comment]
so the newest version is just broken?

**Comment by cosigyn** [comment]
It seems to affect old versions too

**Comment by YukiAyase** [comment]
Install the non-ASP.NET Core version aka regular .NET Core 3.1.12
*This one, which is below ASP.NET Core*
![image](https://github.com/MicaForEveryone/MicaForEveryone/assets/64414315/b83f940c-f655-40a3-a377-e7e090adbab9)

**Comment by alexkisser** [comment]
fixed, thank you
