### ISSUE TITLE
MicaForEveryone won't open despite installing .NET Core

### ISSUE THREAD

**Issue by SKCro** [MicaForEveryone/MicaForEveryone#406]
[✔] This is not about other apps being displayed weird or etc.
[✔] This is not about rendering issues that caused by a bug in the Windows.
[✔] I've read [FAQ](https://github.com/MicaForEveryone/MicaForEveryone/wiki/FAQ).
[✔] I've checked other issues and this is not a duplicate.

**Describe the bug**
![image](https://github.com/MicaForEveryone/MicaForEveryone/assets/55817746/8ef3f6d5-1c6b-4097-8c3d-af2f0d023d21)
Upon opening MicaForEveryone, I am greeted by the "You must install .NET Core" dialog, despite the fact that it's already installed (as shown by the window behind it). I also tried the x64 version of the .NET Core package to no avail.

**To Reproduce**
Attempt to run MicaForEveryone on that specific version of Windows I guess?? I'm not too sure if this can even be reproduced on another machine, it might just be a problem with my computer 🤷‍♂️

**Expected behavior**
I expected the program to open, given that I fulfilled its requirement of .NET Core :P

**Screenshots**
See above. Additionally:
![image](https://github.com/MicaForEveryone/MicaForEveryone/assets/55817746/21a640a5-2887-4ca7-a9f7-1c5489589315)

**Windows Version**
Windows 10 LTSC 2019 - Build 17763.5329.

**Additional context**

**Comment by 70V07** [comment]
same problem here

**Comment by TheBrightSoul** [comment]
Same problem I have installed latest version of .net but It didn't work
![image](https://github.com/MicaForEveryone/MicaForEveryone/assets/90372921/db1db045-4fd6-4a29-b763-55c78108b2ea)

**Comment by TheBrightSoul** [comment]
> Same problem I have installed latest version of .net but It didn't work ![image](https://private-user-images.githubusercontent.com/90372921/302979176-db1db045-4fd6-4a29-b763-55c78108b2ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMDkzNzMsIm5iZiI6MTcwNzMwOTA3MywicGF0aCI6Ii85MDM3MjkyMS8zMDI5NzkxNzYtZGIxZGIwNDUtNGZkNi00YTI5LWI3NjMtNTVjNzgxMDhiMmVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDEyMzExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhYjY5ODQ4MzZiNDkzNDA5ZTUwZjBjNDU2ZjdhODdlNzlkNDMyMjg3NzkwMDM3MTQyYTJhMTQ2NmVkMzAyYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0PLejMPYr-_Tstq5IkgNMwxZ41B6ynZLKDl4VN4KbI4)

Is there an Specific version of .net we need to instll or something like that??? because I am getting the same problem in a software called Handbreak(used to compress video records)

**Comment by TheBrightSoul** [comment]
> > Same problem I have installed latest version of .net but It didn't work ![image](https://private-user-images.githubusercontent.com/90372921/302979176-db1db045-4fd6-4a29-b763-55c78108b2ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMDkzNzMsIm5iZiI6MTcwNzMwOTA3MywicGF0aCI6Ii85MDM3MjkyMS8zMDI5NzkxNzYtZGIxZGIwNDUtNGZkNi00YTI5LWI3NjMtNTVjNzgxMDhiMmVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDEyMzExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhYjY5ODQ4MzZiNDkzNDA5ZTUwZjBjNDU2ZjdhODdlNzlkNDMyMjg3NzkwMDM3MTQyYTJhMTQ2NmVkMzAyYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0PLejMPYr-_Tstq5IkgNMwxZ41B6ynZLKDl4VN4KbI4)
> 
> Is there an Specific version of .net we need to instll or something like that??? because I am getting the same problem in a software called Handbreak(used to compress video records)

An update to this is that I have tried intsalling other versions of donet but nothing works ( versions mentioned in attched image below:

![image](https://github.com/MicaForEveryone/MicaForEveryone/assets/90372921/d518330f-d2cc-4d32-9ad9-f63ab35faa70)

**Comment by TheBrightSoul** [comment]
> > Same problem I have installed latest version of .net but It didn't work ![image](https://private-user-images.githubusercontent.com/90372921/302979176-db1db045-4fd6-4a29-b763-55c78108b2ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMDkzNzMsIm5iZiI6MTcwNzMwOTA3MywicGF0aCI6Ii85MDM3MjkyMS8zMDI5NzkxNzYtZGIxZGIwNDUtNGZkNi00YTI5LWI3NjMtNTVjNzgxMDhiMmVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDEyMzExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhYjY5ODQ4MzZiNDkzNDA5ZTUwZjBjNDU2ZjdhODdlNzlkNDMyMjg3NzkwMDM3MTQyYTJhMTQ2NmVkMzAyYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0PLejMPYr-_Tstq5IkgNMwxZ41B6ynZLKDl4VN4KbI4)
> 
> Is there an Specific version of .net we need to instll or something like that??? because I am getting the same problem in a software called Handbreak(used to compress video records)

Dude I feel like I am spamming this but here is one more thing I thought I should tell (in the following image I have tried some more of Runtime and now I am obsessed with runtime) I am smoking Runtime now IDK why it's not working
![image](https://github.com/MicaForEveryone/MicaForEveryone/assets/90372921/94dac38e-61d9-4432-966d-bce59fbb8994)

**Comment by SKCro** [comment]
Closing because I got it working on a newer version of Windows. The version I was using was too old for MFE to be useful anyway.
