### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by ha2ked** [MicaForEveryone/MicaForEveryone#434]
I am on tiny11 so that may be the problem but mica works on nothing. Any help pls

**Comment by GMFocalFossa** [comment]
I use windows11. Same.

**Comment by swanlon** [comment]
Same here, it wont open anymore

**Comment by SaiyajinK** [comment]
[1.3.0.0](https://github.com/MicaForEveryone/MicaForEveryone/releases/tag/v1.3.0.0) version works fine on w11 pro 24h2 (build 26100.712) 👍🏻 

![image](https://github.com/MicaForEveryone/MicaForEveryone/assets/105972098/5fd9ce3e-7510-4833-8603-74e665cc6792)

**Comment by CitrusLinux** [comment]
I found out if you have an app open and change your system color to another one it activates, but if you close and reopen any app Ex. explorer.exe it goes away

**Comment by CitrusLinux** [comment]
UPDATE: I found a way to get it to work, you need to enable Extend Frame Into Client Area to get it to work, Do this for every item!

**Comment by swanlon** [comment]
Did a complete uninstall and downgraded to 1.3.0.0 and it's working now, thank you @SaiyajinK
