### ISSUE TITLE
`To run this application, you must install .NET Core.  However, I have already installed .NET Core

### ISSUE THREAD

**Issue by mkanet** [MicaForEveryone/MicaForEveryone#450]
[x] This is not about other apps being displayed weird or etc.
[x] This is not about rendering issues that caused by a bug in the Windows.
[x] I've read [FAQ](https://github.com/MicaForEveryone/MicaForEveryone/wiki/FAQ).
[x] I've checked other issues and this is not a duplicate.

**Describe the bug**
```To run this application, you must install .NET Core.  Would you like to download now?```

![image](https://github.com/user-attachments/assets/e5db95d2-59e0-4c23-a31e-eb5a21056fb5)

I already have the latest .NET versions installed and in my system path:
`C:\Program Files\dotnet\` is in my SYSTEM path.

Here is all the versions I currently have;  I even rebooted after installing the .NET Core. 
```
dotnet --list-runtimes

Microsoft.NETCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
However, the app still prompts me to install ".NET Core".  The documentation doesnt mention a specific version; hence. I downloaded the latest non-beta official versions.  

**Windows Version**
Windows 10 build 22H2

**Comment by Alvaro-Eduardo482** [comment]
Facing the same issue in windows 11 23H2.

**Comment by Rufistofeles** [comment]
The version needed is 3.1

https://dotnet.microsoft.com/en-us/download/dotnet/3.1

**Comment by mkanet** [comment]
I didnt notice any instructions specifying what version number is required for MicaForEveryone.
