### ISSUE TITLE
Font rendering problems in Light mode

### ISSUE THREAD

**Issue by tmprnc** [MicaForEveryone/MicaForEveryone#462]
[x] This is not about other apps being displayed weird or etc.
[x] This is not about rendering issues that caused by a bug in the Windows.
[x] I've read [FAQ](https://github.com/MicaForEveryone/MicaForEveryone/wiki/FAQ).
[x] I've checked other issues and this is not a duplicate.

**Describe the bug**
Fonts look extremely weird (practically washed out) on any apps that use "Extend frame into client area" when using Light mode. This is particularly noticeable on the native Windows file open dialog on such apps.
The issue does not occur in Dark mode.
Fonts look significantly more aliased and sometimes outright washed out and unreadable. Furthermore, the transparency effect does not seem noticeable in Light mode.

I do use MacType which normally improves Windows font rendering, however this issue still occurs on a computer which does not have MacType installed (as it has a much higher screen resolution while being a laptop with a smaller screen, rendering better font rendering unnecessary) as well as when turning off MacType on this computer.

**To Reproduce**
1. Turn on Windows light mode on apps.
2. Enable extend frame into client area.
3. Use a number of apps that use Win32 UI components (such as 7Zip) or the native file open dialog from Windows (in Vivaldi browser in this case)

**Screenshots**
![1728405271](https://github.com/user-attachments/assets/993a0ea7-4fa7-4fda-a453-317151d04ad3)
![1728405559](https://github.com/user-attachments/assets/55191c1a-4a3b-4d04-8df1-1c71e6fad3ef)

**Windows Version**
Windows 11 Pro, Insider Beta channel, version 23H2 build 22635.4300.
My GPU is a NVIDIA GeForce 3070, my drivers are up to date.

**Additional context**
I am also using the following applications:
- **MacType, which _MAY_ interfere, since this is a font related issue. However, I have tried this while disabling MacType, and the issue still occurs.**
- AutoDarkMode, which should have no impact on the windows themselves.
- TranslucentTB, which should have no impact on the windows themselves.

**Comment by dare25GH** [comment]
It's happening because the font is 'transparent' if you change the background color or image to a dark one, the font is more visible. Not a solution, but a hack I currently use.
