### ISSUE TITLE
Mica for Everyone asks for .NET Core even tho its installed

### ISSUE THREAD

**Issue by salrn** [MicaForEveryone/MicaForEveryone#467]
[ ] This is not about other apps being displayed weird or etc.
[ ] This is not about rendering issues that caused by a bug in the Windows.
[ ] I've read [FAQ](https://github.com/MicaForEveryone/MicaForEveryone/wiki/FAQ).
[ ] I've checked other issues and this is not a duplicate.

**Describe the bug**
Lauching Mica for Everyone asks to install .NET Core which ive already installed (3.1.32 and 8.0.403) Pressing yes on the promt seems to do nothing

**To Reproduce**
Open MFA I guess?

**Expected behavior**
MFA Not launching

**Screenshots**
![Screenshot 2024-10-26 101915](https://github.com/user-attachments/assets/53366667-c9fd-4c25-9269-0c46d4b58dee)

**Windows Version**
Windows 11 Pro 24H2

**Additional context**
-

**Comment by not-Kacper** [comment]
Hey bro did solve it? cuz i run to same problem

**Comment by luiza177** [comment]
I have the same issue. I'm on version 2.0.3.0 Windows 11 Pro 23h2

**Comment by dongle-the-gadget** [comment]
Version 2 shouldn't ask for .NET Core, it is bundled within the app itself now.
