### ISSUE TITLE
Flower launcher weird mica background

### ISSUE THREAD

**Issue by daFoggo** [MicaForEveryone/MicaForEveryone#483]
[X ] I've read [FAQ](https://github.com/MicaForEveryone/MicaForEveryone/wiki/FAQ).
[X ] I've restarted the affected app after adding rule for it.
[ X] I've checked other issues and this is not a duplicate.

**Describe the bug**
I'm using Flow launcher. I Installed Mica for other usage, not Flow launcher. But currently I have a problem with Flow launcher, the overflowing background appear when I turn it on ( see the image )
**Rule**
backdrop type - mica
corner mode - rounded

**Target Application**
- Flow launcher
- ver 1.19.4

**To Reproduce**
- Alt space to toggle Flow launcher

- Blur background 

**Expected behavior**
No background behind or if mica can interact with flow launcher, it should make mica effect. 

**Screenshots**
![image](https://github.com/user-attachments/assets/c2c309d2-05ef-4bc3-bfdf-07c11b1f6e7f)

**Windows Version**
Win11 23H2

**Other tools being used**

**Additional context**

**Comment by Skyyblaze** [comment]
You have to set all rules to Default and restart Flow, then it should be fixed.
