### ISSUE TITLE
Split "Blur Backdrop" from "Blur Behind"

### ISSUE THREAD

**Issue by AndromedaMelody** [MicaForEveryone/MicaForEveryone#55]
Windows OS have 5 types of backdrop: 

- Aero Glass (used in Vista/Win7)
- Blur (first appeared in Win10 Build10074, designed for StartMenu and TaskBar , make them look beautiful in early version of Win10)
- Acrylic (gradually replace Blur after Win10 1709)
- Mica
- Tabbed

DwmEnableBlurBehindWindow is a API which is first introduced in Vista. It is designed for Aero Glass and make developers use Aero Glass in their application easily. So it has no connection with Blur Backdrop.

Blur Backdrop usually use SetWindowCompositionAttribute to enable and it is prove that Start Menu uses it.

I think it is necessary to split "Blur Backdrop" from "Blur Behind" Feature, and move "Blur Backdrop" into "Backdrop Type ComboBox.

Also, SetWindowCompositionAttribute can enable Acrylic before 22523, so I think it is better to make Win10 and Win11(Build22000) to select this type of backdrop.

Thank you.

**Comment by dongle-the-gadget** [comment]
Using `SetWindowCompositionAttribute` causes some particularly odd behaviors, such as extending the glass frame into the window, whereas `DWMWA_SYSTEMBACKDROP_TYPE` only apply the effect on the frame.

**Comment by dongle-the-gadget** [comment]
The "Blur Behind" feature in MFE is actually `SetWindowCompositionAttribute`.

**Comment by AndromedaMelody** [comment]
> The "Blur Behind" feature in MFE is actually `SetWindowCompositionAttribute`.

I think it is better to remove DwmEnableBlurBehindWindow Function, because it may make static texts blurring in some application (such as Win32/MFC Dialog). DwmEnableBlurBehindWindow is suitable for Aero Glass. In Window with Aero Glass, static texts can shown like Win7 title bar text.
Essentially, Blur(`SetWindowCompositionAttribute`) is backdrop. It should put it into Backdrop Type ComboBox and it shouldn't have interconnection with BlurBehind (`DwmEnableBlurBehindWindow `)

**Comment by AndromedaMelody** [comment]
> Using `SetWindowCompositionAttribute` causes some particularly odd behaviors, such as extending the glass frame into the window, and causes weird glitches in some builds; whereas `DWMWA_SYSTEMBACKDROP_TYPE` only apply the effect on the frame.

In my opinion, some dangerous option can put into advance settings and introduce risk. Users have choice to enable or disable it

**Comment by minusium** [comment]
> I think it is necessary to split "Blur Backdrop" from "Blur Behind" Feature, and move "Blur Backdrop" into "Backdrop Type ComboBox.

I don't agree. It's better now like this.

**Comment by dongle-the-gadget** [comment]
> Essentially, Blur (enabled by SetWindowCompositionAttribute) is backdrop.
We used the API name to refer to this backdrop.
