### ISSUE TITLE
Add an option to hide taskbar icon

### ISSUE THREAD

**Issue by VitalSkib** [MicaForEveryone/MicaForEveryone#56]
Not much of an issue though, but I wonder if there is a setting to hide taskbar icon? 
If not, please add the ability to hide it.
As for me, ones it configured, it is not necessary for frequent access. 
And if necessary, you can always create a shortcut on the desktop.
TIA

**Comment by dongle-the-gadget** [comment]
I believe that users should just manually put it on the desktop instead of having the app doing it.

**Comment by VitalSkib** [comment]
> I believe that users should just manually put it on the desktop instead of having the app doing it.
Could you elaborate what did you mean please?
Thank you.

**Comment by dongle-the-gadget** [comment]
The app shouldn't pin itself on the desktop.

**Comment by VitalSkib** [comment]
> The app shouldn't pin itself on the desktop.

Um, it seems you did not understand my original question. 
I did not ask about the icons on the Desktop, I asked about the icon in the Taskbar (System Tray, to be more precise).
And not just hide it in a hidden panel (flyout?), but to get rid of it completely from the System Tray.

![2022-05-03](https://user-images.githubusercontent.com/43848892/166440757-c325ddc9-0729-4171-9ca6-33c52e3b0c05.jpg)

**Comment by Axer128** [comment]
+1.
Annoying to use the windows hide/show tray icons feature, because by default it always hides new icons, and you cannot adjust that.. I prefer all new apps to show there icon by default for security.. So can't get around that.

So yea option to hide it wuld be nice.

Or just a simple optional "headless" / CLI build that doesn't have a gui or tray icon and just looks at hte config file would suffice too.

**Comment by DjZiio** [comment]
I think an option to hide or change the systray icon would be really appreciated. Its quite blocky and bright blue and doesn't look good with my dark theme or any color theme that's not complementary.. I'd be happy with a manual way to change the icon or disable it as well, if anyone knows if this is possible.

**Comment by xmine64** [comment]
Done in commit [20c31afd091932b0d837820e495a82d3b6dc8f5a](20c31afd091932b0d837820e495a82d3b6dc8f5a).

**Comment by VitalSkib** [comment]
> Done in commit [20c31afd091932b0d837820e495a82d3b6dc8f5a](https://github.com/MicaForEveryone/MicaForEveryone/commit/20c31afd091932b0d837820e495a82d3b6dc8f5a).

Oh, cool, if so. 
Thanks for this.. 
However, excuse me for ignorance, but how can I use it? 
Or will it be available in the next MFE update?

**Comment by dongle-the-gadget** [comment]
You can download the latest builds by going to Actions.

**Comment by VitalSkib** [comment]
> You can download the latest builds by going to Actions.

Thank you very much.. 
Although, using the `MicaForEveryone-x64-Release-Installer` I get some errors (see the attached image). 
And by installing it using the `MicaForEveryone-x64-Release.msixbundle`, I was finally able to get the working MFE.

![mfe_error](https://user-images.githubusercontent.com/43848892/198876402-0eec6eef-c74f-409a-856d-6a4a4a38133d.PNG)

**Comment by xmine64** [comment]
> Although, using the MicaForEveryone-x64-Release-Installer I get some errors

Weird, it was working when I tested it. I'll investigate this.
