### ISSUE TITLE
Dark theme for menu bar

### ISSUE THREAD

**Issue by m1sh3r** [MicaForEveryone/MicaForEveryone#57]
![Снимок экрана 2022-04-02 131547](https://user-images.githubusercontent.com/84245138/161378650-1742d836-0936-4d1f-89cf-cb561efaf93b.png)
Is it really possible to make a dark theme for this header? Sometimes it doesn't look very good, especially in applications from Adobe (After Effects and Premiere Pro)

**Comment by minusium** [comment]
MFE just works on system frame (titlebar and border), it doesn't have anything to do with other components.

**Comment by m1sh3r** [comment]
And what are the ways to paint this part of the window?

**Comment by minusium** [comment]
It depends on the target app, I don't know and it's not part of MFE's job.

**Comment by dongle-the-gadget** [comment]
I believe it's some kind of uxtheme.dll undocumented APIs in uxtheme.dll (haven't tried tho).

**Comment by rounk-ctrl** [comment]
nah you have to use UAH messages to custom paint it before the window is created.

**Comment by Void48** [comment]
> ![image](https://user-images.githubusercontent.com/70931017/165125328-851de682-ffd8-4806-aaa4-6f35bb4991fc.png) it looks idk

looks alright. can this be added to MFE?

**Comment by Void48** [comment]
> > custom paint it before the HWND is created
> 
> 
> 
> MFE only picks up windows after it has been created, so the method doesn't work.

Ah I see
