### ISSUE TITLE
Firefox doesn't respect "System" title bar color

### ISSUE THREAD

**Issue by maicol07** [MicaForEveryone/MicaForEveryone#64]
Hi,
I'm using [Auto Dark Mode](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode) to automatically switch dark/light theme at a specific time, but MFE seems not changing automatically to light/dark mode when it changes automatically (I've set the color to System). This should be added to MFE.
Thanks

**Comment by minusium** [comment]
MFE already responses to change of system theme mode, I've tested it and it works. I'm not sure what's wrong with it on your system. You can check if its Settings app responses to theme change or not. if it does then it means it detects that your theme is changed. Then check rules.

**Comment by dongle-the-gadget** [comment]
What applications have you tested, and have you made sure that:
1/ the window doesn't implement a custom title bar (MFE won't work on those)
2/ the window isn't defined as an exception (MFE has default rules excluding Explorer and MSPaint by default)

**Comment by dongle-the-gadget** [comment]
Oh yeah, I can repo this.

**Comment by dongle-the-gadget** [comment]
Unfortunately, I cannot determine the problem within MFE, as it sets the immersive dark mode properly.

**Comment by maicol07** [comment]
I've found a workaround for this issue: I've written an AutoHotKey script that automatically triggers reload when theme has changed and Firefox window is active (or is opened):
https://github.com/maicol07/AHK-scripts/blob/main/FixFirefoxMFE.ahk

Feel free to improve the script if you want!
