### ISSUE TITLE
[MSIX] Unable to be installed on w11 22610 due to it being signed with an untrusted certificate.

### ISSUE THREAD

**Issue by spectrapulse** [MicaForEveryone/MicaForEveryone#67]
When Installing Windows will refuse to install the app (And I've not managed to find a way around it)
```This app package is not signed with a trusted certificate. Contact your system administrator or the app developer to obtain a new certificate or app package with trusted certificates. The root certificate and all immediate certificates of the signature in the app package must be trusted (0x800B010A)```

**Comment by xmine64** [comment]
It's not an issue. I already know that. I did it myself because I don't own a trusted certificate. You can sign it with your own certificate or add my certificate to your trusted root.

> The .msixbundle file contains both of x64 and arm64 builds, with .NET Core Runtime. For installing it first you need to register its certificate.
> 
> * Simply right click the MSIX and click Properties
> * Go to Digital signatures Tab
> * Select Minusium and click Details
> * In next popup select View Certificate
> * In next popup select Install Certificate
> * In next step select Local machine (If a user account prompt appear click yes)
> * Select Place all certificates in Following store and click browse select Trusted People and click OK and Next
> * Click Finish
> * Confirmation windows will appear After that Try Installing the MSIX

**Comment by spectrapulse** [comment]
It would be nice if this could be added to the FAQ section of the wiki...

**Comment by RespectMathias** [comment]
This should be on the learn page for sideloading

**Comment by zaeboba** [comment]
I installed the certificate, but the error is the same.
