### ISSUE TITLE
Accent Color Tint with Mica/Acrylic/Tabbed

### ISSUE THREAD

**Issue by RibShark** [MicaForEveryone/MicaForEveryone#68]
When the backdrop type is set to "None", and "Show accent color on title bars and window borders" is set in the Windows settings, the titlebar and backdrop will be tinted to the accent color:
![image](https://user-images.githubusercontent.com/1957489/166816487-7fd02fca-e287-4524-b49c-57e5b1c36d60.png)

I would really appreciate it if there were to be a way to tint Mica/Acrylic/Tabbed backdrops too; right now when the accent color is set to show, it causes the main titlebar to simply not have a backdrop at all, and the extended frame to not have any tint:
![image](https://user-images.githubusercontent.com/1957489/166816704-4bf2eae7-edf5-4af3-a267-f28a4af90efa.png)

Ideally, in this scenario, the entire titlebar/menubar should be tinted blue, on top of the selected backdrop (so translucent blue in the case of acrylic), somewhat mimicking the Win7 aero look when the color is customized.

**Comment by dongle-the-gadget** [comment]
Impossible for us.
