### ISSUE TITLE
File Explorer client area resets to default material after losing focus

### ISSUE THREAD

**Issue by ashergz** [MicaForEveryone/MicaForEveryone#71]
https://user-images.githubusercontent.com/35883201/170076226-0088f6a2-b28c-42b2-983c-c7451da485f8.mp4

**Comment by chuck00000** [comment]
![image](https://user-images.githubusercontent.com/98159699/170610299-4a37ae61-24ee-4d66-9a34-cb02dabed1bc.png)
![image](https://user-images.githubusercontent.com/98159699/170610346-694f8008-06dc-4d7b-b670-4250844dec7d.png)
It always does, after mininize the window, resize the window

**Comment by dongle-the-gadget** [comment]
Unfortunately, there's pretty much nothing we can do about this, as this is a problem within File Explorer, and not Mica For Everyone.

`ExtendFrameIntoClientArea` is also an unsupported flag, so behaviors like this are expected.

**Comment by ashergz** [comment]
That's sad to know. Is there any workaround to prevent or at least reenable mica material in the client area once it has reset?

**Comment by dongle-the-gadget** [comment]
These are the only solutions I know to help: https://github.com/MicaForEveryone/MicaForEveryone/issues/69#issuecomment-1127558545
