### ISSUE TITLE
Add a option to completely ignore certain processes (Issue with FluentSearch application)

### ISSUE THREAD

**Issue by Skyyblaze** [MicaForEveryone/MicaForEveryone#72]
Would it be possible to add an option to MicaForEveryone so it completely ignores hooking into certain processes? As it stands running MicaForEveryone causes the application FluentSearch (https://github.com/adirh3/Fluent-Search) to have a weird, super thick border around its window:

![grafik](https://user-images.githubusercontent.com/22203339/170511324-8febe06a-b56c-4ff4-a5bc-367925317f29.png)

This happens no matter the settings in MicaForEveryone even if I specifically target FluentSearch.

**Comment by xmine64** [comment]
Add a rule then put everything on default.

**Comment by Skyyblaze** [comment]
I swear I tried this before opening the issue, now I rebooted Windows due to something else and it works, sorry about that o.o

**Comment by xmine64** [comment]
> I swear I tried this before opening the issue, now I rebooted Windows due to something else and it works, sorry about that o.o

I see, you should close the app and then open it again to remove the applied effects. I explained it in the settings app.
