### ISSUE TITLE
MFE Crashes when config reloads too often

### ISSUE THREAD

**Issue by dr-baba** [MicaForEveryone/MicaForEveryone#74]
I have created a keyboard shortcut using ahk to reload MFE config due to the issue of file explorer losing mica when resized/maximised etc. I have bound this to Displayfusion so that when maximised, it reloads the config automatically. However when I use the shortcut too often, MFE crashes from reloading config file too often.

**Comment by Hawksprey420** [comment]
![image](https://user-images.githubusercontent.com/75325547/174181023-d00ae094-22f5-4c6e-979e-4f83105593f3.png)
Here are the crash logs I have obtained from Event Viewer

**Comment by xmine64** [comment]
I tried to fix this using a mutex, but reloading config file and reapplying rules too often is not recommended because it may put your CPU on pressure.
