### ISSUE TITLE
Is it safe at all to put MicaForEveryone into efficiency mode in the Task Manager? 

### ISSUE THREAD

**Issue by younyokel** [MicaForEveryone/MicaForEveryone#75]
I don't know how much this tool loads the computer, but I was just wondering if there would be errors if I put MicaForEveryone in efficiency mode (that's the one in Task Manager).

**Comment by xmine64** [comment]
Idk I didn't try. the app listens for window creation event, and unless you open a new window it's in idle mode and doesn't use your CPU resources.
