### ISSUE TITLE
Gamebar overlay makes the entire screen white while mica for everyone is running

### ISSUE THREAD

**Issue by shahiljain** [MicaForEveryone/MicaForEveryone#76]
### System Details
Windows 11 22H2
Mica For Everyone Version 1.0.6.2
### The Bug
![image](https://user-images.githubusercontent.com/75173792/172168019-aecf0ef6-a470-465c-8938-efa8ab98f8b0.png)
It happens even when anything in the overlay is pinned making it useless.

### Steps to recreate
Run Mica for everyone.
Then Run Gamebar.
Note: It might work for a while if launched before Mica for Everyone but will eventually become the same when removed from ram.

### What I tried
Adding a different rules for GameBar and GambarFTServer, nothing worked.

**Comment by dongle-the-gadget** [comment]
@xmine64, probably relevant to you.
