### ISSUE TITLE
Support for varying levels of acrylic opacity and luminosity for theming?

### ISSUE THREAD

**Issue by Hawksprey420** [MicaForEveryone/MicaForEveryone#81]
I've been using MicaForEveryone for the past 2 to 3 days, and while I loved the idea of hooking the app into theming applications with acrylic and mica, I do wonder if you guys can put out support for modifying the acrylic material to support luminosity and opacity for the theming since I do want more control on how the acrylic looks.

**Comment by dongle-the-gadget** [comment]
#70
