### ISSUE TITLE
Cert not work

### ISSUE THREAD

**Issue by p6002** [MicaForEveryone/MicaForEveryone#84]
Cert is outdated or something. Not work even if cert is installed.

**Comment by xmine64** [comment]
I'll check, thanks for report

**Comment by Aritz331** [comment]
@p6002 have you installed it correctly?

**Comment by p6002** [comment]
Yes, right click on .bin, and install cert in settings.

**Comment by Aritz331** [comment]
its a .msixbundle, not .bin

**Comment by p6002** [comment]
Yes, this file:
MicaForEveryone-v1.0.6.2-x64-Release

**Comment by dongle-the-gadget** [comment]
The certificate of the latest release is still valid. Have you made sure that you installed the certificate correctly? I personally would install it in Local Machine, Trusted People store. Automatic **DOES NOT** work.

**Comment by p6002** [comment]
Installation process is too difficult. Already delete this app.

**Comment by Aritz331** [comment]
@p6002 its not that difficult, you just have to install a certificate before installing it
