### ISSUE TITLE
WDADesktopService

### ISSUE THREAD

**Issue by JotaRata** [MicaForEveryone/MicaForEveryone#86]
Has anyone encountered with a little gray rectangle that appears in the bottom right corner of your screen, when pressing Alt+Tab the process is named WDADesktopService and it is started among with MicaForEveryone.

![imagen](https://user-images.githubusercontent.com/36273501/174578840-dcb515f6-6081-443f-933d-61f7e61ed14a.png)

![imagen](https://user-images.githubusercontent.com/36273501/174578894-30c6cacf-4e59-443e-b337-7c299d02f816.png)

Is there a fix for this?

**Comment by dongle-the-gadget** [comment]
What is the executable properties?

**Comment by JotaRata** [comment]
Nevermind, it was the Microsoft Wireless display adapter app.
By coincidence it happens to open at the same time as Mica giving the impression that it was some sort of sub-process.
