### ISSUE TITLE
Add French Translation

### ISSUE THREAD

**Issue by SaiyajinK** [MicaForEveryone/MicaForEveryone#88]
hi @xmine64  

I translated the app to French but I don't know how to submit/add it?

as I can't add it myself I give it to you so that you can integrate the translation !
I upload the file here: [french translation.zip](https://github.com/MicaForEveryone/MicaForEveryone/files/8967885/french.translation.zip)

It should therefore be added the folder -fr- to the following directory : MicaForEveryone/MicaForEveryone.UI/Strings/

Thank for your confirmation 👍

**Comment by xmine64** [comment]
We need a document on translation guide.
