### ISSUE TITLE
Update 1.6.0.2 to 1.6.0.3 ok ! but now, Mica won't launch... :'(

### ISSUE THREAD

**Issue by gsrd90** [MicaForEveryone/MicaForEveryone#90]
Hi guys, 

today I downloaded the new version of mica (v1.0.6.3) but it refuses to start... :/
> I did not change anything on my pc and the previous version (v1.0.6.2) worked and still works like a charm. 👍 

-

On my pc, I have all the necessary redistributables (I think) : [https://i.imgur.com/00ioWi5.png](https://i.imgur.com/00ioWi5.png)
and this is what the event viewer shows me : [https://i.imgur.com/IHDatHM.png](https://i.imgur.com/IHDatHM.png)

-

any idea please? I am very enthusiastic for this new version because I saw that the program was finally translated into French and I can't wait to use it like this!

thank you for your feedback!

**Comment by xmine64** [comment]
I guess it's a build error, I tested it before uploading but I'll test it again.

**Comment by gsrd90** [comment]
It works ! Fast and efficient, thank you ! 👍💯

**Comment by gsrd90** [comment]
solved.

**Comment by xmine64** [comment]
Enjoy yourself🙌
