### ISSUE TITLE
Doesn't work on electron apps 

### ISSUE THREAD

**Issue by RyzenDew** [MicaForEveryone/MicaForEveryone#97]
this doesn't work on apps like
Discord
Cider 
Youtube music

Can someone add support for that please thank you!

**Comment by xmine64** [comment]
MFE only works on system frame, supporting apps like Discord is not our goal. But there may be patches for these apps like https://github.com/mazOnGitHub/discord-mica

**Comment by RyzenDew** [comment]
That isnt real mica thats faked been there done that and did a way better job then them thanks anyway

**Comment by Grafaffel** [comment]
> That isnt real mica thats faked been there done that and did a way better job then them thanks anyway

for it to work in electron apps you need the background to be transparent (setting for ig. Vencord (Discord Client Mod)) and have a theme that makes parts of the HTML transparent.

**Comment by Skyyblaze** [comment]
@Grafaffel that still only allows for Acrylic with Discord and not Mica or Mica Alt with MFE right? I use it exactly like you say but I have to enable "Blur Behind" for Discord in MFE and that's always Acrylic.
