### ISSUE TITLE
Possible feature?

### ISSUE THREAD

**Issue by KrazyLurt** [MicaForEveryone/MicaForEveryone#99]
First off, great application, been using it for a long time, simple brilliant.

I wonder if its possible to add some kind of a feature to adjust the background color of the title bar mica?

See attached picture where I have used a lighter shade of grey for windows explorer.

It's more prominent with the Windows Terminal where the background is completely black.
![terminal](https://user-images.githubusercontent.com/75538575/178124626-f578fc4d-ff6b-4b8c-94ca-b086a6bab2c1.png)

![concept2](https://user-images.githubusercontent.com/75538575/178124645-72a9cc39-e41f-4275-93c3-0b26cbceb5fd.png)

**Comment by dongle-the-gadget** [comment]
I don't quite understand your request. If I understood you correctly, you want some way to customize the material?

**Comment by KrazyLurt** [comment]
I mean the color behind the tab. The actual tab have a nice Micha effect, but the black background around the tab in the title bar is more or less pitch black and doesn't IMO doesn't match esthetically

**Comment by dongle-the-gadget** [comment]
Can't you change the material of Explorer from Tabbed to Mica?

**Comment by KrazyLurt** [comment]
Good idea , but that changes the color of the tab to a lighter color and that looks worse sadly

**Comment by dongle-the-gadget** [comment]
Unfortunately, that's the only level of customization we can deliever without any hooks or modifications to Windows.

**Comment by KrazyLurt** [comment]
Okay, that's good to know. Thanks for the replies, and keep up the good work! =)
